
:experimental:
include::{partialsdir}/entities.adoc[]

[[chap-introduction]]
= Introduction

This guide covers installation of Fedora, a Linux distribution built on free and open source software. This manual helps you install Fedora on desktops, laptops, and servers. The installation system is easy to use even if you lack previous knowledge of Linux or computer networks. If you select default options, Fedora provides a complete desktop operating system, including productivity applications, Internet utilities, and desktop tools.

This document details the full range of installation options, including those that apply only in limited or unusual circumstances. Understanding of all topics described in this document is not necessary to successfully perform the installation in most cases.

[[sect-introduction-background]]
== Background

[[sect-introduction-about]]
=== About Fedora

To find out more about {PRODUCT}, visit the link:++https://fedoraproject.org/++[{PRODUCT} Project Website]. Other documentation describing additional topics related to {PRODUCT} is available at link:++https://docs.fedoraproject.org/++[{PRODUCT} Documentation]. Also see the link:++https://fedoraproject.org/wiki/Fedora_Project_Wiki++[{PRODUCT} Project Wiki].

[[sect-introduction-additional-help]]
=== Getting Additional Help

If you encounter any problems which are not described in documentation, you might get help from members of the community - developers, users, and others. There are many ways to get help: the Ask Fedora website, mailing lists, forums, or IRC. For a summary of available resources, see the link:++https://fedoraproject.org/wiki/Communicating_and_getting_help++[Communicating and Getting Help] page on the {PRODUCT} wiki.

[[sect-introduction-about-document]]
== About This Document

[[sect-introduction-goals]]
=== Goals

This guide helps a reader:

* Understand how to locate the {PRODUCT} distribution online

* Create configuration data that allows a computer to boot {PRODUCT}

* Understand and interact with the {PRODUCT} installation program

* Complete basic post-installation configuration of a {PRODUCT} system

[NOTE]
====

This guide does not cover *use* of {PRODUCT}. To learn how to use an installed {PRODUCT} system, see the other manuals available at link:++https://docs.fedoraproject.org/++[Fedora Documentation].

====

[[sect-introduction-target-audience]]
=== Target Audience

This guide is intended for {PRODUCT} users of all levels of experience. However, it describes the installation process and its many options in far greater detail than most users are likely to require. You do not need to read and understand this entire document to install {PRODUCT} on a computer. This document is most likely to help experienced users perform advanced and unusual installations.
