:experimental:
:toc: macro
include::{partialsdir}/entities.adoc[]

[[appe-kickstart-syntax-reference]]
= Kickstart Syntax Reference

This appendix describes commands and options available in Kickstart installations. For general information about Kickstart, see xref:advanced/Kickstart_Installations.adoc#chap-kickstart-installations[Automating the Installation with Kickstart].

toc::[]

[IMPORTANT]
====

Device names are not guaranteed to be consistent across reboots, which can complicate usage in Kickstart scripts. When a Kickstart option calls for a device node name (such as `sda`), you can instead use any item from `/dev/disk`. For example, instead of:

[subs="quotes, macros"]
----
[command]#part / --fstype=xfs --onpart=sda1#
----

You could use an entry similar to one of the following:

----

part / --fstype=xfs --onpart=/dev/disk/by-path/pci-0000:00:05.0-scsi-0:0:0:0-part1
part / --fstype=xfs --onpart=/dev/disk/by-id/ata-ST3160815AS_6RA0C882-part1

----

This provides a consistent way to refer to disks that is more meaningful than just `sda`. This is especially useful in large storage environments.

====

While the general principles of Kickstart installations tend to stay the same, the commands and options can change between major releases. You can use the [command]#ksverdiff# command to display the differences between two versions of the Kickstart syntax. This is useful when updating an existing Kickstart file to be used with a new release. To display a list of changes in syntax between Fedora{nbsp}{PREVVER} and {PRODVER}, use the following command:

[subs="quotes, macros, attributes"]
----
$ [command]#ksverdiff -f F{PREVVER} -t F{PRODVER}#
----

The [option]#-f# option specifies the release to start the comparison with, and the [option]#-t# option to specify the release to end with. For additional information, see the `ksverdiff(1)` man page. Also note that you can not use this to display changes in a release that is newer than your system - the version of [package]*pykickstart* on Fedora{nbsp}{PREVVER} can not display changes in Fedora{nbsp}{PRODVER}.

Additionally, you can review the [citetitle]_Fedora{nbsp}{PRODVER} Release Notes_, available at link:++https://docs.fedoraproject.org/++[], for a list of changes.

[NOTE]
====

In the following sections, if an option is followed by an equals mark (`=`), a value must be specified after it. In the example commands, options in square brackets (`[ ]`) are optional arguments for the command.

====

[[sect-kickstart-commands-installation]]
== Installation Methods and Sources

The following commands control the way Fedora will be installed.

[[sect-kickstart-commands-device]]
=== device (optional) - Install Extra Device Drivers

On most PCI systems, the installation program will automatically detect Ethernet and SCSI cards. However, on older systems and some PCI systems, Kickstart requires a hint to find the proper devices. The [command]#device# command, which tells the installation program to install extra modules, uses the following format:

[subs="quotes, macros"]
----
[command]#device _moduleName_ [--opts=]#
----

Replace _moduleName_ with the name of the kernel module which should be installed.

[option]#--opts=#::  Options to pass to the installed kernel module. For example:
+
----
device i2c_piix4 --opts="aic152x=0x340 io=11"
----

[[sect-kickstart-commands-driverdisk]]
=== driverdisk (optional) - Use a Driver Disk

Driver disks can be used during Kickstart installations to provide additional drivers not included by default. You must copy the driver disks's contents to the root directory of a partition on the system's hard drive. Then, you must use the [command]#driverdisk# command to specify that the installation program should look for a driver disk and its location.

[subs="quotes, macros"]
----
[command]#driverdisk _partition_ | --source= | --biospart=#
----

_partition_::  Search for the driver disk image on a local partition. Replace _partition_ with the name of the partition containing the driver disk. Note that the partition must be specified as a full path. For example:
+
[subs="quotes, macros"]
----
[command]#driverdisk /dev/sdb1#
----

[option]#--source=#::  Search for the driver disk in a network location instead of a local partition. For example:
+
[subs="quotes, macros"]
----
[command]#driverdisk --source=ftp://pass:attributes[{blank}]_path/to/dd.img_pass:attributes[{blank}]#
----
+
[subs="quotes, macros"]
----
[command]#driverdisk --source=http://pass:attributes[{blank}]_path/to/dd.img_pass:attributes[{blank}]#
----
+
[subs="quotes, macros"]
----
[command]#driverdisk --source=nfs:pass:attributes[{blank}]_hostname_:/pass:attributes[{blank}]_path/to/dd.img_pass:attributes[{blank}]#
----

[option]#--biospart=#::  BIOS partition containing the driver disk (for example, `82p2`).

[[sect-kickstart-commands-install]]
=== install (required) - Configure Installation Method

The default installation mode. You must specify the type of installation from `cdrom`, `harddrive`, `nfs`, `liveimg`, or `url`. The [command]#install# command and the installation method command must be on separate lines. For example:

[subs="quotes, macros"]
----

[command]#install#
[command]#liveimg --url=file:///images/install/squashfs.img --noverifyssl#

----

The installation method commands are:

[command]#cdrom#::  Install from the first optical (DVD) drive on the system.

[command]#harddrive#::  Install from a tree or full installation ISO image on a local hard drive. The tree or ISO image must be on a file system which is mountable in the installation environment. Supported file systems are `ext2`, `ext3`, `ext4`, `vfat`, or `xfs`.
+
[subs="quotes, macros"]
----

[command]#install#
[command]#harddrive --partition= | --biospart= [--dir=]#

----
+
[option]#--partition=#:::  Partition to install from (such as `sdb2`).
+
[option]#--biospart=#:::  BIOS partition to install from (such as `82p2`).
+
[option]#--dir=#:::  Directory containing the installation tree or ISO image.

[command]#liveimg#::  Install from a disk image instead of packages. The image can be the `squashfs.img` file from a live ISO image, or any file system that the installation media can mount. Supported file systems are `ext2`, `ext3`, `ext4`, `vfat`, and `xfs`.
+
This command also supports installation from tar archives of the root file system. In that case, the file name must end with `.tar`, `.tbz`, `.tgz`, `.txz`, `.tar.bz2`, `tar.gz`, or `tar.xz`.
+
[subs="quotes, macros"]
----

[command]#install#
[command]#liveimg --url=  [--proxy= | --checksum= | --noverifyssl=]#

----
+
[option]#--url=#:::  The location to install from. Supported protocols are `HTTP`, `HTTPS`, `FTP`, and `file`.
+
[option]#--proxy=#:::  Specify an `HTTP`, `HTTPS` or `FTP` proxy to use while performing the installation.
+
[option]#--checksum=#:::  An optional argument with the `SHA256` checksum of the image file, used for integrity verification. If you are using a live image provided by Fedora Project, you can find a list of checksums at link:++https://fedoraproject.org/en/verify++[].
+
[option]#--noverifyssl#:::  Disable SSL verification when connecting to an `HTTPS` server.

[command]#nfs#::  Install from an `NFS` server specified. The NFS server must be exporting the full installation ISO image (such as the {PRODUCT} Server DVD) or its extracted contents.
+
[subs="quotes, macros"]
----

[command]#install#
[command]#nfs --server=  [--dir=] [--opts= ]#

----
+
[option]#--server=#:::  Host name of the server.
+
[option]#--dir=#:::  Directory containing the installation tree or ISO image.
+
[option]#--opts=#:::  Mount options to use for mounting the `NFS` export.

[command]#url#::  Install from a tree on a remote server via `HTTP`, `HTTPS`, or `FTP`.
+
[subs="quotes, macros"]
----

[command]#install#
[command]#url --url= | --mirrorlist= [--proxy= | --noverifyssl]#

----
+
[option]#--url=#:::  The location to install from. Supported protocols are `http`, `https`, `ftp`, and `file`.
+
[option]#--mirrorlist=#:::  The mirror URL to install from.
+
[option]#--proxy=#:::  Specify an `HTTP`, `HTTPS` or `FTP` proxy to use while performing the installation.
+
[option]#--noverifyssl#:::  Disable SSL verification when connecting to an `HTTPS` server.

[[sect-kickstart-commands-mediacheck]]
=== mediacheck (optional) - Verify Installation Media Integrity

This command will force the installation program to perform a media check before starting the installation, similarly to the [option]#rd.live.check# boot option (see xref:advanced/Boot_Options.adoc#sect-boot-options-mediacheck[Verifying Boot Media]. This command requires that installations be attended, so it is disabled by default.

[[sect-kickstart-commands-ostreesetup]]
=== ostreesetup (optional) - Install from an OSTree

Used for OSTree installations. See link:++https://wiki.gnome.org/action/show/Projects/OSTree++[] for more information about OSTree. Available options are:

[option]#--osname=#::  Management root for OS installation (required).

[option]#--remote=#::  Management root for OS installation (optional).

[option]#--url=#::  Repository URL (required).

[option]#--ref=#::  Name of branch inside the repository (required).

[option]#--nogpg#::  Disable GPG key verification (optional).

[[sect-kickstart-commands-repo]]
=== repo (optional) - Configure Additional Repositories

Configures additional [application]*DNF* repositories that may be used as sources for package installation. This command can be used multiple times in a single Kickstart file.

See the [citetitle]_Fedora System Administrator's Guide_, available at link:++https://docs.fedoraproject.org/++[], for information about the [application]*DNF* package manager.

[IMPORTANT]
====

Repositories used for installation must be stable. The installation may fail if a repository is modified before the installation concludes.

====

[option]#--name=#::  The repository ID. This option is required. If a repository has a name which conflicts with another previously added repository, it will be ignored. Because the installation program uses a list of pre-configured repositories, this means that you cannot add repositories with the same names as the preconfigured ones.

[option]#--baseurl=#::  The repository URL. The variables that may be used in [application]*DNF* repo configuration files are *not* supported. You may use one of either this option or [option]#--mirrorlist#, not both.

[option]#--mirrorlist=#::  The URL pointing at a list of mirrors for the repository. The variables that may normally be used in dnf repository configuration files are not supported here. You may use one of either this option or --baseurl, not both.

[option]#--install#::  Make the repository configured in the Kickstart file available on the system after the installation as well. Creates a configuration file for the repository in `/etc/yum.repos.d/` on the installed system.

[option]#--cost=#::  An integer value to assign a cost to this repository. If multiple repositories provide the same packages, this number will be used to prioritize which repository will be used before another. Repositories with a lower cost take priority over repositories with higher cost.

[option]#--excludepkgs=#::  A comma-separated list of package names that must *not* be pulled from this repository. This is useful if multiple repositories provide the same package and you want to make sure it comes from a particular repository. Both full package names (such as `publican`) and globs (such as `gnome-*`) are accepted.

[option]#--includepkgs=#::  A comma-separated list of package names and globs that must be pulled from this repository. This is useful if multiple repositories provide the same package and you want to make sure it comes from this repository.

[option]#--proxy=#::  Specify an `HTTP`, `HTTPS` or `FTP` proxy server to use when accessing this repository. This setting does not affect any other repositories or installation sources.

[option]#--ignoregroups=true#::  This option is used when composing installation trees and has no effect on the installation process itself. It tells the compose tools to not look at the package group information when mirroring trees so as to avoid mirroring large amounts of unnecessary data.

[option]#--noverifyssl#::  Disable SSL verification when connecting to an `HTTPS` server.

[[sect-kickstart-commands-url]]
=== url (optional) - Install from an installation tree on a remote server via FTP or HTTP.

Install from an installation tree on a remote server via FTP or HTTP.

[option]#--proxy=#::  Specify an HTTP/HTTPS/FTP proxy to use while performing the install. The various parts of the argument act like you would expect. The syntax is:
+
[subs="quotes, macros"]
----
[protocol://][username[:password]@]host[:port]
----

[option]#--noverifyssl#::  For a tree on a HTTPS server do not check the server’s certificate with what well-known CA validate and do not check the server’s host name matches the certificate’s domain name.

[option]#--url=#::  The URL to install from. Variable substitution is done for `$releasever` and `$basearch` in the URL.

[option]#--mirrorlist=#::  The mirror URL to install from. Variable substitution is done for `$releasever` and `$basearch` in the URL.

[option]#--metalink=#::  The metalink URL to install from. Variable substitution is done for `$releasever` and `$basearch` in the URL.

[[sect-kickstart-commands-storage]]
== Storage and Partitioning

Commands in this section are used to determine your system's storage options and partitioning.

[[sect-kickstart-commands-autopart]]
=== autopart (optional) - Automatic Partitioning

Automatically creates partitions: a root (`/`) partition (1 GB or larger), a `swap` partition, and an appropriate `/boot` partition for the architecture. On large enough drives (50{nbsp}GB and larger), this also creates a `/home` partition.

[IMPORTANT]
====

The [command]#autopart# option cannot be used together with the [command]#part/partition#, [command]#raid#, [command]#logvol#, or [command]#volgroup# options in the same Kickstart file.

====

[option]#--type=#::  Selects one of the predefined automatic partitioning schemes you want to use. Accepts the following values:
+
** `lvm`: The LVM partitioning scheme.
+
** `btrfs`: The Btrfs partitioning scheme.
+
** `plain`: Regular partitions with no LVM or Btrfs.
+
** `thinp`: The LVM Thin Provisioning partitioning scheme.
+
The created partitioning scheme will follow the recommended scheme described at xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-manual-partitioning-recommended[Recommended Partitioning Scheme].

[option]#--fstype=#::  Specify a supported file system (such as `ext4` or `xfs`) to replace the default when doing automatic partitioning.

[option]#--nolvm#::  Do not use LVM or Btrfs for automatic partitioning. This option is equal to [option]#--type=plain#.

[option]#--encrypted#::  Encrypts all partitions. This is equivalent to checking the `Encrypt partitions` check box on the initial partitioning screen during a manual graphical installation.

[option]#--passphrase=#::  Provides a default system-wide passphrase for all encrypted devices.

[option]#--escrowcert=pass:attributes[{blank}]_URL_of_X.509_certificate_pass:attributes[{blank}]#::  Stores data encryption keys of all encrypted volumes as files in `/root`, encrypted using the X.509 certificate from the URL specified with _URL_of_X.509_certificate_. The keys are stored as a separate file for each encrypted volume. This option is only meaningful if [option]#--encrypted# is specified.

[option]#--backuppassphrase#::  Adds a randomly-generated passphrase to each encrypted volume. Store these passphrases in separate files in `/root`, encrypted using the X.509 certificate specified with [option]#--escrowcert#. This option is only meaningful if [option]#--escrowcert# is specified.

[option]#--cipher=#::  Specifies which type of encryption will be used if the [application]*Anaconda* default `aes-xts-plain64` is not satisfactory. You must use this option together with the [option]#--encrypted# option; by itself it has no effect. Available types of encryption are listed in the [citetitle]_Fedora Security Guide_, available at link:++https://docs.fedoraproject.org/++[]. Using either `aes-xts-plain64` or `aes-cbc-essiv:sha256` is strongly recommended.

[option]#--luks-version=#::  Specifies which version of LUKS should be used to encrypt the system. Only relevant if [option]#--encrypted# is also specified.

[option]#--pbkdf=#::  Sets Password-Based Key Derivation Function (PBKDF) algorithm for the LUKS keyslot. Only relevant if [option]#--encrypted# is also specified. See the `cryptsetup(8)` man page for more information.

[option]#pbkdf-memory=#::  Sets the memory cost for PBKDF. Only relevant if [option]#--encrypted# is also specified. See the `cryptsetup(8)` man page for more information.

[option]#pbkdf-time=#::  Sets the number of miliseconds to spend with PBKDF passphrase processing. Only relevant if [option]#--encrypted# is also specified. See information about the [option]#--iter-time# option in the `cryptsetup(8)` man page for more information.
+
Only one of [option]#--pbkdf-time=# or [option]#--pbkdf-iterations=# can be specified at the same time.

[option]#pbkdf-iterations=#::  Sets the number of iterations for passphrase processing directly, and avoids PBKDF benchmark. Only relevant if [option]#--encrypted# is also specified. See information about the [option]#--pbkdf-force-iterations# option in the `cryptsetup(8)` man page for more information.
+
Only one of [option]#--pbkdf-time=# or [option]#--pbkdf-iterations=# can be specified at the same time.

[[sect-kickstart-commands-bootloader]]
=== bootloader (required) - Configure Boot Loader

Specifies how the boot loader should be installed.

[IMPORTANT]
====

You should always use a password to protect your boot loader. An unprotected boot loader can allow a potential attacker to modify the system's boot options and gain unauthorized access to the system.

====

[IMPORTANT]
====

Some systems require a special partition for installing the boot loader. The type and size of this partition depends on whether the disk you are installing the boot loader to uses the _Master Boot Record_ (MBR) or a _GUID Partition Table_ (GPT) schema. For more information, see xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-storage-partitioning-bootloader[Boot Loader Installation].

====

[option]#--append=#::  Specifies additional kernel parameters. To specify multiple parameters, separate them with spaces. For example:
+
[subs="quotes, macros"]
----
[command]#bootloader --location=mbr --append="hdd=ide-scsi ide=nodma"#
----
+
The [option]#rhgb# and [option]#quiet# parameters are always used, even if you do not specify them here or do not use the [option]#--append=# command at all.

[option]#--boot-drive=#::  Specifies which drive the boot loader should be written to, and therefore which drive the computer will boot from. If you use a multipath device as the boot drive, specify only one member of the device.
+
[IMPORTANT]
====

The [option]#--boot-drive=# option is currently being ignored in {PRODUCT} installations on IBM System{nbsp}z systems using the [application]*zipl* boot loader. When [application]*zipl* is installed, it determines the boot drive on its own.

====
+
*Not* specifying this option will result in the following behavior:
+
.. If the [option]#--driveorder=# option was used, [application]*Anaconda* will install the boot loader on the first valid device specified in the drive order.
+
.. The first present and valid disk containing a `/boot` partition will be used.
+
.. If none of the above applies, then the first valid storage device from the list of all detected devices will be used to install the boot loader.

[option]#--leavebootorder#::  Prevents the installation program from making changes to the existing list of bootable images on UEFI or ISeries/PSeries systems.

[option]#--driveorder=#::  Specifies which drive is first in the BIOS boot order. For example:
+
[subs="quotes, macros"]
----
[command]#bootloader --driveorder=sda,hda#
----

[option]#--location=#::  Specifies where the boot record is written. Valid values are the following:
+
** `mbr` - The default option. Depends on whether the drive uses the Master Boot Record (MBR) or GUID Partition Table (GPT) scheme:
+
*** On a GPT-formatted disk, this option will install stage 1.5 of the boot loader into the BIOS boot partition.
+
*** On an MBR-formatted disk, stage 1.5 will be installed into the empty space between the MBR and the first partition.
+
** `partition` - Install the boot loader on the first sector of the partition containing the kernel.
+
** `none` - Do not install the boot loader.
+
In most cases, this option does not need to be specified.

[option]#--password=#::  If using [application]*GRUB2* as the boot loader, sets the boot loader password to the one specified with this option. This should be used to restrict access to the [application]*GRUB2* shell, where arbitrary kernel options can be passed.
+
If a password is specified, [application]*GRUB2* will also ask for a user name. The user name is always `root`.

[option]#--iscrypted#::  Normally, when you specify a boot loader password using the [option]#--password=# option, it will be stored in the Kickstart file in plain text. If you want to encrypt the password, use this option and an encrypted password.
+
To generate an encrypted password, use the [command]#grub2-mkpasswd-pbkdf2# command, enter the password you want to use, and copy the command's output (the hash starting with `grub.pbkdf2`) into the Kickstart file. An example [command]#bootloader# Kickstart entry with an encrypted password will look similar to the following:
+
[subs="quotes, macros"]
----

[command]#bootloader --iscrypted --password=grub.pbkdf2.sha512.10000.5520C6C9832F3AC3D149AC0B24BE69E2D4FB0DBEEDBD29CA1D30A044DE2645C4C7A291E585D4DC43F8A4D82479F8B95CA4BA4381F8550510B75E8E0BB2938990.C688B6F0EF935701FF9BD1A8EC7FE5BD2333799C98F28420C5CC8F1A2A233DE22C83705BB614EA17F3FDFDF4AC2161CEA3384E56EB38A2E39102F5334C47405E#

----

[option]#--timeout=#::  Specifies the amount of time the boot loader will wait before booting the default option (in seconds).

[option]#--default=#::  Sets the default boot image in the boot loader configuration.

[option]#--extlinux#::  Use the [application]*extlinux* boot loader instead of [application]*GRUB2*. This option only works on systems supported by [application]*extlinux*.

[option]#--disabled#::  Do not attempt to install a boot loader. This option overrides all other boot loader configuration; all other boot loader options will be ignored and no boot loader packages will be installed.

[option]#--nombr#::  Install the boot loader configuration and support files, but do not modify the MBR.

[[sect-kickstart-commands-btrfs]]
=== btrfs (optional) - Create Btrfs Volume or Subvolume

Create a Btrfs volume or subvolume. For a volume, the syntax is:

[subs="quotes, macros"]
----

[command]#btrfs _mntpoint_ --data=pass:attributes[{blank}]_level_ --metadata=pass:attributes[{blank}]_level_ [--label=] _partitions_pass:attributes[{blank}]#

----

One or more partitions can be specified in _partitions_. When specifying more than one partitions, the entries must be separated by a single space. See xref:exam-kickstart-create-btrfs[Creating Btrfs Volumes and Subvolumes] for a demonstration.

For a subvolume, the syntax is:

[subs="quotes, macros"]
----

[command]#btrfs _mntpoint_ --subvol --name=pass:attributes[{blank}]_name_ _parent_pass:attributes[{blank}]#

----

_parent_ should be the identifier of the subvolume's parent volume, _name_ with a name for the subvolume, and _mntpoint_ is the location where the file system is mounted.

[option]#--data=#::  RAID level to use for file system *data* (such as `0`, `1`, or `10`). This parameter is optional, has no meaning for subvolumes, and requires more than one physical disk.

[option]#--metadata=#::  RAID level to use for file system/volume *metadata* (such as `0`, `1`, or `10`). This parameter is optional, has no meaning for subvolumes, and requires more than one physical disk.

[option]#--label=#::  Specify a label for the Btrfs file system. If the given label is already in use by another file system, a new label will be created. This option has no meaning for subvolumes.

[option]#--subvol#::  Create a Btrfs subvolume instead of a volume.

[option]#--name=#::  Set a name for a Btrfs subvolume.

[option]#--noformat# or [option]#--useexisting#::  Use an existing Btrfs volume (or subvolume) and do not reformat the file system.

[option]#--mkfsoptions=#::  Specifies additional parameters to be passed to the program that makes a filesystem on this volume or subvolume. No processing is done on the list of arguments, so they must be supplied in a format that can be passed directly to the mkfs program. This means multiple options should be comma-separated or surrounded by double quotes, depending on the filesystem.

The following example shows how to create a Btrfs volume from member partitions on three disks with subvolumes for `/` and `/home`. The main volume is not mounted or used directly in this example.

[[exam-kickstart-create-btrfs]]
.Creating Btrfs Volumes and Subvolumes
====

[subs="quotes, macros, attributes"]
----

[command]#part btrfs.01 --size=6000 --ondisk=sda#
[command]#part btrfs.02 --size=6000 --ondisk=sdb#
[command]#part btrfs.03 --size=6000 --ondisk=sdc#

[command]#btrfs none --data=0 --metadata=1 --label=f{PRODVER} btrfs.01 btrfs.02 btrfs.03#
[command]#btrfs / --subvol --name=root LABEL=f{PRODVER}#
[command]#btrfs /home --subvol --name=home f{PRODVER}#

----

====

[[sect-kickstart-commands-clearpart]]
=== clearpart (optional) - Remove All Existing Partitions

Removes partitions from the system, prior to creation of new partitions. By default, no partitions are removed.

[NOTE]
====

If the [command]#clearpart# command is used, then the [command]#part --onpart# command cannot be used on a logical partition.

====

For a detailed example of partitioning including the [command]#clearpart# command, see xref:sect-kickstart-example-advanced-partitioning[Advanced Partitioning Example].

[option]#--all#::  Erases all partitions from the system.
+
[WARNING]
====

This option will erase all disks which can be reached by the installer, including any attached network storage. Use this option with caution.

====

[option]#--drives=#::  Specifies which drives to clear partitions from. For example, the following clears all the partitions on the first two drives on the primary IDE controller:
+
[subs="quotes, macros"]
----
[command]#clearpart --drives=hda,hdb --all#
----
+
To clear a multipath device, use the format `disk/by-id/scsi-_WWID_pass:attributes[{blank}]`, where _WWID_ is the _world-wide identifier_ for the device. For example, to clear a disk with WWID `58095BEC5510947BE8C0360F604351918`, use:
+
[subs="quotes, macros"]
----
[command]#clearpart --drives=disk/by-id/scsi-58095BEC5510947BE8C0360F604351918#
----
+
This format is preferable for all multipath devices, but if errors arise, multipath devices that do not use _logical volume management_ (LVM) can also be cleared using the format `disk/by-id/dm-uuid-mpath-_WWID_pass:attributes[{blank}]`, where _WWID_ is the _world-wide identifier_ for the device. For example, to clear a disk with WWID `2416CD96995134CA5D787F00A5AA11017`, use:
+
[subs="quotes, macros"]
----
[command]#clearpart --drives=disk/by-id/dm-uuid-mpath-2416CD96995134CA5D787F00A5AA11017#
----
+
[WARNING]
====

Never specify multipath devices by device names like `mpatha`. Device names such as this are not specific to a particular disk. The disk named `/dev/mpatha` during installation might not be the one that you expect it to be. Therefore, the [command]#clearpart# command could target the wrong disk.

====
+
Starting with Fedora 25, you can combine multiple ways of specifying storage targets in one command, using the pipe ("pass:attributes[{blank}]`|`pass:attributes[{blank}]") as a delimiter. For example:
+
----
clearpart --drives=sd*|hd*|vda,/dev/vdc
----
+
The above will match either of `sd*`, `hd*`, *or* `vda` *and* `/dev/vdc`. Variants are processed from left to right, and at least one of them must match for the command to succeed.

[option]#--list=#::  Specifies which partitions to clear. This option overrides the [option]#--all# and [option]#--linux# options if used. Can be used across different drives. For example:
+
[subs="quotes, macros"]
----
[command]#clearpart --list=sda2,sda3,sdb1#
----

[option]#--disklabel=#::  Create a set disk label when relabeling a disk.

[option]#--linux#::  Erases all Linux partitions.

[option]#--none#::  Do not remove any partitions. This is the default behavior - using this option is the same as not using the [command]#clearpart# command at all.

[NOTE]
====

Using the [command]#clearpart --all# command in a Kickstart file to remove all existing partitions during the installation will cause [application]*Anaconda* to pause and prompt you for a confirmation. If you need to perform the installation automatically with no interaction, add the [command]#zerombr# command to your Kickstart file.

====

[[sect-kickstart-commands-fcoe]]
=== fcoe (optional) - Configure Fibre Channel Over Ethernet Devices

Specify which FCoE devices should be activated automatically in addition to those discovered by _Enhanced Disk Drive Services_ (EDD).

[subs="quotes, macros"]
----
[command]#fcoe --nic=pass:attributes[{blank}]_name_ [--dcp= | --autovlan]#
----

[option]#--nic=# (required)::  Name of the device to be activated.

[option]#--dcb=#::  Establish _Data Center Bridging_ (DCB) settings.

[option]#--autovlan#::  Discover VLANs automatically.

[[sect-kickstart-commands-ignoredisk]]
=== ignoredisk (optional) - Ignore Specified Disks

Causes the installation program to ignore the specified disks. This is useful if you use autopartition and want to be sure that some disks are ignored. For example, without [command]#ignoredisk#, attempting to deploy on a SAN cluster the Kickstart would fail, as the installation program detects passive paths to the SAN that return no partition table.

[subs="quotes, macros"]
----
[command]#ignoredisk --drives= | --only-use= [--interactive]#
----

[option]#--drives=#::  Specify one or more drives to ignore. Multiple drives can be specified as a comma-separated list. For example:
+
[subs="quotes, macros"]
----
[command]#ignoredisk --drives=sda,sdc#
----
+
To ignore a multipath device that does not use _logical volume management_ (LVM), use the format `disk/by-id/dm-uuid-mpath-_WWID_pass:attributes[{blank}]`, where _WWID_ is the _world-wide identifier_ for the device. For example, to ignore a disk with WWID `2416CD96995134CA5D787F00A5AA11017`, use:
+
[subs="quotes, macros"]
----
[command]#ignoredisk --drives=disk/by-id/dm-uuid-mpath-2416CD96995134CA5D787F00A5AA11017#
----
+
Multipath devices that use LVM are not assembled until after [application]*Anaconda* has parsed the Kickstart file. Therefore, you cannot specify these devices in the format `dm-uuid-mpath`. Instead, to ignore a multipath device that uses LVM, use the format `disk/by-id/scsi-_WWID_pass:attributes[{blank}]`, where _WWID_ is the _world-wide identifier_ for the device. For example, to ignore a disk with WWID `58095BEC5510947BE8C0360F604351918`, use:
+
[subs="quotes, macros"]
----
[command]#ignoredisk --drives=disk/by-id/scsi-58095BEC5510947BE8C0360F604351918#
----
+
[WARNING]
====

Never specify multipath devices by device names like `mpatha`. Device names such as this are not specific to a particular disk. The disk named `/dev/mpatha` during installation might not be the one that you expect it to be. Therefore, the [command]#clearpart# command could target the wrong disk.

====
+
Starting with Fedora 25, you can combine multiple ways of specifying storage targets in one command, using the pipe ("pass:attributes[{blank}]`|`pass:attributes[{blank}]") as a delimiter. For example:
+
----
ignoredisk --drives=sd*|hd*|vda,/dev/vdc
----
+
The above will match either of `sd*`, `hd*`, *or* `vda` *and* `/dev/vdc`. Variants are processed from left to right, and at least one of them must match for the command to succeed.

[option]#--only-use=#::  Specifies a list of disks for the installation program to use. All other disks are ignored. For example, to use disk `sda` during installation and ignore all other disks:
+
[subs="quotes, macros"]
----
[command]#ignoredisk --only-use=sda#
----
+
To include a multipath device that does not use LVM:
+
[subs="quotes, macros"]
----
[command]#ignoredisk --only-use=disk/by-id/dm-uuid-mpath-2416CD96995134CA5D787F00A5AA11017#
----
+
To include a multipath device that uses LVM:
+
[subs="quotes, macros"]
----
[command]#ignoredisk --only-use=disk/by-id/scsi-58095BEC5510947BE8C0360F604351918#
----

[option]#--interactive#::  Allows you to manually navigate the advanced storage screen.

[[sect-kickstart-commands-iscsi]]
=== iscsi (optional) - Configure iSCSI Devices

Specifies additional iSCSI storage to be attached during installation. If you use the [command]#iscsi# command, you must also assign a name to the iSCSI node, using the [command]#iscsiname# command (see xref:sect-kickstart-commands-iscsiname[iscsiname (optional) - Assign Name to iSCSI Device]. The [command]#iscsiname# command must appear before the [command]#iscsi# command in the Kickstart file.

You should configure iSCSI storage in the system BIOS or firmware (iBFT for Intel systems) rather than use the [command]#iscsi# command if possible. If you do so, [application]*Anaconda* automatically detects and uses disks configured in BIOS or firmware and no special configuration is necessary in the Kickstart file.

If you must use the [command]#iscsi# command, make sure that networking is activated at the beginning of the installation, and that the [command]#iscsi# command appears in the Kickstart file *before* you refer to iSCSI disks with commands such as [command]#clearpart# or [command]#ignoredisk#.

[subs="quotes, macros"]
----
[command]#iscsi --ipaddr=  --port=  [--target= | --iface= | --user= | --password= | --reverse-user= | --reverse-password=]#
----

[option]#--ipaddr=#::  The IP address of the target to connect to.

[option]#--port=#::  The port number (typically `3260`).

[option]#--target=#::  Target _IQN_ (iSCSI Qualified Name).

[option]#--iface=#::  Bind the connection to a specific network interface instead of using the default one determined by the network layer. Once used, it must be specified in all instances of the [command]#iscsi# command in the entire Kickstart file.

[option]#--user=#::  User name required to authenticate with the target.

[option]#--password=#::  Password that corresponds with the user name specified for the target.

[option]#--reverse-user=#::  User name required to authenticate with the initiator from a target using reverse CHAP authentication.

[option]#--reverse-password=#::  Password that corresponds with the user name specified for the initiator.

[[sect-kickstart-commands-iscsiname]]
=== iscsiname (optional) - Assign Name to iSCSI Device

Assigns a name to an iSCSI node specified by the [command]#iscsi# command (xref:sect-kickstart-commands-iscsi[iscsi (optional) - Configure iSCSI Devices]). This command is mandatory if you use the [command]#iscsi# command, and it must be specified *before* you use [command]#iscsi#.

[subs="quotes, macros"]
----
[command]#iscsiname _iqn_pass:attributes[{blank}]#
----

[[sect-kickstart-commands-logvol]]
=== logvol (optional) - Create LVM Logical Volume

Create a logical volume for Logical Volume Management (LVM) with the syntax:

[subs="quotes, macros"]
----
[command]#logvol _mntpoint_ --vgname=  --name= [pass:attributes[{blank}]_options_pass:attributes[{blank}]]#
----

[NOTE]
====

Do not use the dash (`-`) character in logical volume and volume group names when installing {PRODUCT} using Kickstart. If this character is used, the installation will finish normally, but the `/dev/mapper/` directory will list these volumes and volume groups with every dash doubled. For example, a volume group named `volgrp-01` containing a logical volume named `logvol-01` will be listed as `/dev/mapper/volgrp--01-logvol--01`.

This limitation only applies to newly created logical volume and volume group names. If you are reusing existing ones using the [option]#--noformat# or [option]#--useexisting# option, their names will not be changed.

====

For a detailed example of [command]#logvol# in action, see xref:sect-kickstart-example-advanced-partitioning[Advanced Partitioning Example].

_mntpoint_::  Replace with the volume's mount point. This name can take the following forms:
+
`/pass:attributes[{blank}]_path_pass:attributes[{blank}]`:::  A path to the mount point - for example, `/` or `/home`
+
`swap`:::  The partition is used as swap space.
+
To determine the size of the swap partition automatically, use the [option]#--recommended# option:
+
[subs="quotes, macros"]
----
`swap --recommended`
----
+
To determine the size of the swap partition automatically but also allow extra space for your system to hibernate, use the [option]#--hibernation# option:
+
[subs="quotes, macros"]
----
`swap --hibernation`
----
+
The size assigned will be equivalent to the swap space assigned by [option]#--recommended# plus the amount of RAM on your system.
+
For the swap sizes assigned by these commands, see the section describing swap in xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-manual-partitioning-recommended[Recommended Partitioning Scheme].
+
`none`:::  Used only when creating a thin pool volume.

[option]#--noformat#::  Use an existing logical volume and do not format it.

[option]#--useexisting#::  Use an existing logical volume and format it.

[option]#--fstype=#::  Sets the file system type for the logical volume. Valid values are `xfs`, `ext2`, `ext3`, `ext4`, `swap`, and `vfat`. See xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-manual-partitioning-filesystems[Device, File System and RAID Types] for information about available file systems.

[option]#--fsoptions=#::  Specifies a free form string of options to be used when mounting the filesystem. This string will be copied into the `/etc/fstab` file of the installed system and should be enclosed in quotes. For example:
+
[subs="quotes, macros"]
----
[option]#--fsoptions="ro, x-systemd.device-timeout=0"#
----

[option]#--mkfsoptions=#::  Specifies additional parameters to be passed to the program that makes a filesystem on this logical volume. No processing is done on the list of arguments, so they must be supplied in a format that can be passed directly to the mkfs program. This means multiple options should be comma-separated or surrounded by double quotes, depending on the filesystem.

[option]#--label=#::  Sets a label for the logical volume.

[option]#--grow#::  Grow the volume to fill available space (if any), or up to the limit set by the [option]#--maxsize=# option.

[option]#--size=#::  The size of the logical volume in megabytes. This option can not be used together with the [option]#--percent=# option.

[option]#--percent=#::  Specify the amount by which to grow the logical volume, as a percentage of the free space in the volume group after any statically-sized logical volumes are taken into account. This option can not be used together with the [option]#--size=# and [option]#--grow# options.
+
[IMPORTANT]
====

When creating a new logical volume, you must either specify its size statically using the [option]#--size=# option, or as a percentage of remaining free space using the [option]#--percent=# option. You can not use both of these options on the same logical volume.

====

[option]#--maxsize=#::  The maximum size in megabytes when the logical volume is set to grow. Specify an integer value here such as `500` (do not include the unit).

[option]#--recommended#::  Use this option when creating a `swap` logical volume to determine the size of this volume automatically, based on your system's hardware. For details about the recommended scheme, see xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-manual-partitioning-recommended[Recommended Partitioning Scheme].
+
[IMPORTANT]
====

This option can only be used for partitions which result in a file system such as the `/boot` partition and `swap` space. It can not be used to create partitionsm, LVM physical or logical volumes or RAID members.

====

[option]#--resize#::  Resize an existing logical volume. If you use this option, you must also specify [option]#--useexisting# and [option]#--size#.

[option]#--encrypted#::  Specifies that this logical volume should be encrypted, using the passphrase provided in the [option]#--passphrase=# option. If you do not specify a passphrase, the installation program will use the default, system-wide passphrase set with the [command]#autopart --passphrase# command, or stop the installation and prompt you to provide a passphrase if no default is set.

[option]#--passphrase=#::  Specifies the passphrase to use when encrypting this logical volume. You must use this option together with the [option]#--encrypted# option. This option has no effect by itself.

[option]#--cipher=#::  Specifies which type of encryption will be used if the [application]*Anaconda* default `aes-xts-plain64` is not satisfactory. You must use this option together with the [option]#--encrypted# option; by itself it has no effect. Available types of encryption are listed in the [citetitle]_Fedora Security Guide_, available at link:++https://docs.fedoraproject.org/++[]. Using either `aes-xts-plain64` or `aes-cbc-essiv:sha256` is strongly recommended.

[option]#--escrowcert=pass:attributes[{blank}]_URL_of_X.509_certificate_pass:attributes[{blank}]#::  Store data encryption keys of all encrypted volumes as files in `/root`, encrypted using the X.509 certificate from the URL specified with _URL_of_X.509_certificate_. The keys are stored as a separate file for each encrypted volume. This option is only meaningful if [option]#--encrypted# is specified.

[option]#--backuppassphrase#::  Add a randomly-generated passphrase to each encrypted volume. Store these passphrases in separate files in `/root`, encrypted using the X.509 certificate specified with [option]#--escrowcert#. This option is only meaningful if [option]#--escrowcert# is specified.

[option]#--thinpool#::  Creates a thin pool logical volume. (Use a mount point of `none`)

[option]#--metadatasize=#::  Metadata area size (in MiB) for a new thin pool device.

[option]#--chunksize=#::  Chunk size (in KiB) for a new thin pool device.

[option]#--thin#::  Create a thin logical volume. (Requires use of [option]#--poolname#)

[option]#--poolname=#::  Specify the name of the thin pool in which to create a thin logical volume. Requires the [option]#--thin# option.

[option]#--profile=#::  Specify the configuration profile name to use with thin logical volumes. If used, the name will also be included in the metadata for the given logical volume. By default, the available profiles are `default` and `thin-performance` and are defined in the `/etc/lvm/profile` directory. See the `lvm(8)` man page for additional information.

[option]#--cachepvs=#::  A comma-separated list of (fast) physical volumes which should be used for LVM cache.

[option]#--cachesize=#::  Requested size of cache attached to the logical volume, in MiB. (Requires the [option]#--cachepvs=# option.)

[option]#--cachemode=#::  Mode to be used for LVM cache (either `writeback` or `writethrough`).

[NOTE]
====

The [option]#--cachepvs=#, [option]#--cachesize=#, and [option]#--cachemode=# options listed above are used to configure LVM caching. For more information, see the `lvmcache(7)` man page.

====

[option]#--luks-version=#::  Specifies which version of LUKS should be used to encrypt the system. Only relevant if [option]#--encrypted# is also specified.

[option]#--pbkdf=#::  Sets Password-Based Key Derivation Function (PBKDF) algorithm for the LUKS keyslot. Only relevant if [option]#--encrypted# is also specified. See the `cryptsetup(8)` man page for more information.

[option]#pbkdf-memory=#::  Sets the memory cost for PBKDF. Only relevant if [option]#--encrypted# is also specified. See the `cryptsetup(8)` man page for more information.

[option]#pbkdf-time=#::  Sets the number of miliseconds to spend with PBKDF passphrase processing. Only relevant if [option]#--encrypted# is also specified. See information about the [option]#--iter-time# option in the `cryptsetup(8)` man page for more information.
+
Only one of [option]#--pbkdf-time=# or [option]#--pbkdf-iterations=# can be specified at the same time.

[option]#pbkdf-iterations=#::  Sets the number of iterations for passphrase processing directly, and avoids PBKDF benchmark. Only relevant if [option]#--encrypted# is also specified. See information about the [option]#--pbkdf-force-iterations# option in the `cryptsetup(8)` man page for more information.
+
Only one of [option]#--pbkdf-time=# or [option]#--pbkdf-iterations=# can be specified at the same time.

Create one or more partitions first using xref:sect-kickstart-commands-part[part (required) - Create Physical Partition], create the logical volume group (xref:sect-kickstart-commands-volgroup[volgroup (optional) - Create LVM Volume Group]), and then create logical volumes. For example:

[subs="quotes, macros"]
----

[command]#part pv.01 --size 3000#
[command]#volgroup myvg pv.01#
[command]#logvol / --vgname=myvg --size=2000 --name=rootvol#

----

[[sect-kickstart-commands-part]]
=== part (required) - Create Physical Partition

Creates a partition on the system.

For a detailed example of [command]#part# in action, see xref:sect-kickstart-example-advanced-partitioning[Advanced Partitioning Example].

[subs="quotes, macros"]
----

[command]#part|partition _mntpoint_ --name=pass:attributes[{blank}]_name_ --device=pass:attributes[{blank}]_device_ --rule=pass:attributes[{blank}]_rule_ [pass:attributes[{blank}]_options_pass:attributes[{blank}]]#

----

[WARNING]
====

All partitions created are formatted as part of the installation process unless [option]#--noformat# and [option]#--onpart=# are used.

====

[NOTE]
====

If partitioning fails for any reason, diagnostic messages appear on virtual console 3.

====

_mntpoint_::  Where the partition is mounted. The value must be of one of the following:
+
`/pass:attributes[{blank}]_path_pass:attributes[{blank}]`:::  A path to the mount point - for example, `/` or `/home`
+
`swap`:::  The partition is used as swap space.
+
To determine the size of the swap partition automatically, use the [option]#--recommended# option:
+
[subs="quotes, macros"]
----
`swap --recommended`
----
+
The size assigned will be effective but not precisely calibrated for your system.
+
To determine the size of the swap partition automatically but also allow extra space for your system to hibernate, use the [option]#--hibernation# option:
+
[subs="quotes, macros"]
----
`swap--hibernation`
----
+
The size assigned will be equivalent to the swap space assigned by [option]#--recommended# plus the amount of RAM on your system.
+
For the swap sizes assigned by these commands, see the section describing swap in xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-manual-partitioning-recommended[Recommended Partitioning Scheme].
+
`raid._id_pass:attributes[{blank}]`:::  The partition is used for software RAID (see [command]#raid#).
+
`pv._id_pass:attributes[{blank}]`:::  The partition is used for LVM (see xref:sect-kickstart-commands-part[part (required) - Create Physical Partition]).
+
`biosboot`:::  The partition will be used for a BIOS Boot partition. A 1 MB BIOS boot partition is necessary on BIOS-based systems using a _GUID Partition Table_ (GPT); the boot loader will be installed into it. It is not necessary on UEFI systems. Also see xref:sect-kickstart-commands-part[part (required) - Create Physical Partition].
+
`/boot/efi`:::  An EFI System Partition. An EFI partition at least 50 MB in size is necessary on UEFI-based systems; the recommended size is 200 MB. It is not necessary on BIOS systems. Also see xref:sect-kickstart-commands-part[part (required) - Create Physical Partition].

[option]#--size=#::  The minimum partition size in megabytes. Specify an integer value here such as `500` (do not include the unit).
+
[IMPORTANT]
====

If the [option]#--size# value is too small, the installation will fail. Set the [option]#--size# value as the minimum amount of space you require. For size recommendations, see xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-manual-partitioning-recommended[Recommended Partitioning Scheme].

====

[option]#--maxsize=#::  The maximum partition size in megabytes when the partition is set to grow. Specify an integer value here such as `500` (do not include the unit).

[option]#--resize#::  Resize an existing partition. When using this option, specify the new size (in megabytes) using the [option]#--size=# option and the target partition using the [option]#--onpart=# option.

[option]#--grow#::  Tells the partition to grow to fill available space (if any), or up to the maximum size setting.
+
[NOTE]
====

If you use [option]#--grow=# without setting [option]#--maxsize=# on a swap partition, [application]*Anaconda* will limit the maximum size of the swap partition. For systems that have less than 2{nbsp}GB of physical memory, the imposed limit is twice the amount of physical memory. For systems with more than 2{nbsp}GB, the imposed limit is the size of physical memory plus 2{nbsp}GB.

====

[option]#--noformat#::  Specifies that the partition should not be formatted, for use with the [option]#--onpart# command.

[option]#--onpart=# or [option]#--usepart=#::  Specifies the device on which to place the partition. For example:
+
[subs="quotes, macros"]
----
[command]#partition /home --onpart=hda1#
----
+
The above puts `/home` on `/dev/hda1`.
+
These options can also add a partition to a logical volume. For example:
+
[subs="quotes, macros"]
----
[command]#partition pv.1 --onpart=hda2#
----
+
The device must already exist on the system; the [option]#--onpart# option will not create it.

[option]#--ondisk=# or [option]#--ondrive=#::  Forces the partition to be created on a particular disk. For example, [option]#--ondisk=sdb# puts the partition on the second SCSI disk on the system.
+
To specify a multipath device that does not use _logical volume management_ (LVM), use the format `disk/by-id/dm-uuid-mpath-_WWID_pass:attributes[{blank}]`, where _WWID_ is the _world-wide identifier_ for the device. For example, to specify a disk with WWID `2416CD96995134CA5D787F00A5AA11017`, use:
+
[subs="quotes, macros"]
----
[command]#part / --fstype=xfs --grow --asprimary --size=8192 --ondisk=disk/by-id/dm-uuid-mpath-2416CD96995134CA5D787F00A5AA11017#
----
+
Multipath devices that use LVM are not assembled until after [application]*Anaconda* has parsed the Kickstart file. Therefore, you cannot specify these devices in the format `dm-uuid-mpath`. Instead, to specify a multipath device that uses LVM, use the format `disk/by-id/scsi-_WWID_pass:attributes[{blank}]`, where _WWID_ is the _world-wide identifier_ for the device. For example, to specify a disk with WWID `58095BEC5510947BE8C0360F604351918`, use:
+
[subs="quotes, macros"]
----
[command]#part / --fstype=xfs --grow --asprimary --size=8192 --ondisk=disk/by-id/scsi-58095BEC5510947BE8C0360F604351918#
----
+
[WARNING]
====

Never specify multipath devices by device names like `mpatha`. Device names such as this are not specific to a particular disk. The disk named `/dev/mpatha` during installation might not be the one that you expect it to be. Therefore, the [command]#clearpart# command could target the wrong disk.

====
+
Starting with Fedora 25, you can combine multiple ways of specifying storage targets in one command, using the pipe ("pass:attributes[{blank}]`|`pass:attributes[{blank}]") as a delimiter. For example:
+
----
part --onpart=sd*|hd*|vda,/dev/vdc
----
+
The above will match either of `sd*`, `hd*`, *or* `vda` *and* `/dev/vdc`. Variants are processed from left to right, and at least one of them must match for the command to succeed.

[option]#--asprimary#::  Forces the partition to be allocated as a *primary* partition. If the partition cannot be allocated as primary (usually due to too many primary partitions being already allocated), the partitioning process will fail. This option only makes sense when the disk uses a Master Boot Record (MBR); for GUID Partition Table (GPT)-labeled disks this option has no meaning. For information about primary (and extended) partitions, see xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-manual-partitioning-recommended[Recommended Partitioning Scheme].

[option]#--fsprofile=#::  Specifies a _usage type_ to be passed to the program that makes a filesystem on this partition. A usage type defines a variety of tuning parameters to be used when making a filesystem. For this option to work, the filesystem must support the concept of usage types and there must be a configuration file that lists valid types. For `ext2`, `ext3`, `ext4`, this configuration file is `/etc/mke2fs.conf`.

[option]#--fstype=#::  Sets the file system type for the partition. Valid values are `xfs`, `ext2`, `ext3`, `ext4`, `swap`, `vfat`, `efi` and `biosboot`. For information about supported file systems, see xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-manual-partitioning-filesystems[Device, File System and RAID Types].

[option]#--fsoptions=#::  Specifies a free form string of options to be used when mounting the filesystem. This string will be copied into the `/etc/fstab` file of the installed system and should be enclosed in quotes. For example:
+
[subs="quotes, macros"]
----
[option]#--fsoptions="ro, x-systemd.device-timeout=0"#
----

[option]#--mkfsoptions=#::  Specifies additional parameters to be passed to the program that makes a filesystem on this partition. No processing is done on the list of arguments, so they must be supplied in a format that can be passed directly to the mkfs program. This means multiple options should be comma-separated or surrounded by double quotes, depending on the filesystem.

[option]#--label=#::  Assign a label to an individual partition.

[option]#--recommended#::  Determine the size of the partition automatically. For details about the recommended scheme, see xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-manual-partitioning-recommended[Recommended Partitioning Scheme].
+
[IMPORTANT]
====

This option can only be used for partitions which result in a file system such as the `/boot` partition and `swap` space. It can not be used to create partitionsm, LVM physical or logical volumes or RAID members.

====

[option]#--onbiosdisk#::  Forces the partition to be created on a particular disk as discovered by the BIOS.

[option]#--encrypted#::  Specifies that this partition should be encrypted, using the passphrase provided in the [option]#--passphrase# option. If you do not specify a passphrase, [application]*Anaconda* uses the default, system-wide passphrase set with the [command]#autopart --passphrase# command, or stops the installation and prompts you to provide a passphrase if no default is set.

[option]#--passphrase=#::  Specifies the passphrase to use when encrypting this partition. You must use this option together with the [option]#--encrypted# option; by itself it has no effect.

[option]#--cipher=#::  Specifies which type of encryption will be used if the [application]*Anaconda* default `aes-xts-plain64` is not satisfactory. You must use this option together with the [option]#--encrypted# option; by itself it has no effect. Available types of encryption are listed in the [citetitle]_Fedora Security Guide_, available at link:++https://docs.fedoraproject.org/++[]. Using either `aes-xts-plain64` or `aes-cbc-essiv:sha256` is strongly recommended.

[option]#--escrowcert=pass:attributes[{blank}]_URL_of_X.509_certificate_pass:attributes[{blank}]#::  Stores data encryption keys of all encrypted volumes as files in `/root`, encrypted using the X.509 certificate from the URL specified with _URL_of_X.509_certificate_. The keys are stored as a separate file for each encrypted volume. This option is only meaningful if [option]#--encrypted# is specified.

[option]#--backuppassphrase#::  Add a randomly-generated passphrase to each encrypted partition. Store these passphrases in separate files in `/root`, encrypted using the X.509 certificate specified with [option]#--escrowcert#. This option is only meaningful if [option]#--escrowcert# is specified.

[option]#--luks-version=#::  Specifies which version of LUKS should be used to encrypt the system. Only relevant if [option]#--encrypted# is also specified.

[option]#--pbkdf=#::  Sets Password-Based Key Derivation Function (PBKDF) algorithm for the LUKS keyslot. Only relevant if [option]#--encrypted# is also specified. See the `cryptsetup(8)` man page for more information.

[option]#pbkdf-memory=#::  Sets the memory cost for PBKDF. Only relevant if [option]#--encrypted# is also specified. See the `cryptsetup(8)` man page for more information.

[option]#pbkdf-time=#::  Sets the number of miliseconds to spend with PBKDF passphrase processing. Only relevant if [option]#--encrypted# is also specified. See information about the [option]#--iter-time# option in the `cryptsetup(8)` man page for more information.
+
Only one of [option]#--pbkdf-time=# or [option]#--pbkdf-iterations=# can be specified at the same time.

[option]#pbkdf-iterations=#::  Sets the number of iterations for passphrase processing directly, and avoids PBKDF benchmark. Only relevant if [option]#--encrypted# is also specified. See information about the [option]#--pbkdf-force-iterations# option in the `cryptsetup(8)` man page for more information.
+
Only one of [option]#--pbkdf-time=# or [option]#--pbkdf-iterations=# can be specified at the same time.

[[sect-kickstart-commands-raid]]
=== raid (optional) - Create Software RAID

Assembles a software RAID device. This command is of the form:

----

raid mntpoint --level=level --device=mddevice partitions*

----

For a detailed example of [command]#raid# in action, see xref:sect-kickstart-example-advanced-partitioning[Advanced Partitioning Example].

_mntpoint_::  Location where the RAID file system is mounted. If it is `/`, the RAID level must be 1 unless a boot partition (`/boot`) is present. If a boot partition is present, the `/boot` partition must be level 1 and the root (`/`) partition can be any of the available types. The _partitions*_ (which denotes that multiple partitions can be listed) lists the RAID identifiers to add to the RAID array.

[option]#--level=#::  RAID level to use (`0`, `1`, `4`, `5`, `6`, or `10`). See xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-manual-partitioning-filesystems[Device, File System and RAID Types] for information about various RAID types and their requirements.

[option]#--device=#::  Name of the RAID device to use. As of {PRODUCT}{nbsp}{PRODVER}, RAID devices are no longer referred to by names like `md0`. If you have an old (v0.90 metadata) array that you cannot assign a name to, you can specify the array by a filesystem label or UUID (for example, [option]#--device=rhel7-root --label=rhel7-root#).

[option]#--spares=#::  Specifies the number of spare drives allocated for the RAID array. Spare drives are used to rebuild the array in case of drive failure.

[option]#--fsprofile=#::  Specifies a _usage type_ to be passed to the program that makes a filesystem on this partition. A usage type defines a variety of tuning parameters to be used when making a filesystem. For this option to work, the filesystem must support the concept of usage types and there must be a configuration file that lists valid types. For `ext2`, `ext3`, `ext4`, this configuration file is `/etc/mke2fs.conf`.

[option]#--fstype=#::  Sets the file system type for the partition. Valid values are `xfs`, `ext2`, `ext3`, `ext4`, `swap`, `vfat`, `efi` and `biosboot`. For information about supported file systems, see xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-manual-partitioning-filesystems[Device, File System and RAID Types].

[option]#--fsoptions=#::  Specifies a free form string of options to be used when mounting the filesystem. This string will be copied into the `/etc/fstab` file of the installed system and should be enclosed in quotes. For example:
+
[subs="quotes, macros"]
----
[option]#--fsoptions="ro, x-systemd.device-timeout=0"#
----

[option]#--mkfsoptions=#::  Specifies additional parameters to be passed to the program that makes a filesystem on this partition. No processing is done on the list of arguments, so they must be supplied in a format that can be passed directly to the mkfs program. This means multiple options should be comma-separated or surrounded by double quotes, depending on the filesystem.

[option]#--label=#::  Specify the label to give to the filesystem to be made. If the given label is already in use by another filesystem, a new label will be created.

[option]#--noformat#::  Use an existing RAID device and do not format it.

[option]#--useexisting#::  Use an existing RAID device and reformat it.

[option]#--encrypted#::  Specifies that this array should be encrypted, using the passphrase provided in the [option]#--passphrase# option. If you do not specify a passphrase, [application]*Anaconda* uses the default, system-wide passphrase set with the [command]#autopart --passphrase# command, or stops the installation and prompts you to provide a passphrase if no default is set.

[option]#--passphrase=#::  Specifies the passphrase to use when encrypting this partition. You must use this option together with the [option]#--encrypted# option; by itself it has no effect.

[option]#--cipher=#::  Specifies which type of encryption will be used if the [application]*Anaconda* default `aes-xts-plain64` is not satisfactory. You must use this option together with the [option]#--encrypted# option; by itself it has no effect. Available types of encryption are listed in the [citetitle]_Fedora Security Guide_, available at link:++https://docs.fedoraproject.org/++[]. Using either `aes-xts-plain64` or `aes-cbc-essiv:sha256` is strongly recommended.

[option]#--escrowcert=pass:attributes[{blank}]_URL_of_X.509_certificate_pass:attributes[{blank}]#::  Stores data encryption keys of all encrypted volumes as files in `/root`, encrypted using the X.509 certificate from the URL specified with _URL_of_X.509_certificate_. The keys are stored as a separate file for each encrypted volume. This option is only meaningful if [option]#--encrypted# is specified.

[option]#--backuppassphrase#::  Add a randomly-generated passphrase to each encrypted partition. Store these passphrases in separate files in `/root`, encrypted using the X.509 certificate specified with [option]#--escrowcert#. This option is only meaningful if [option]#--escrowcert# is specified.

[option]#--luks-version=#::  Specifies which version of LUKS should be used to encrypt the system. Only relevant if [option]#--encrypted# is also specified.

[option]#--pbkdf=#::  Sets Password-Based Key Derivation Function (PBKDF) algorithm for the LUKS keyslot. Only relevant if [option]#--encrypted# is also specified. See the `cryptsetup(8)` man page for more information.

[option]#pbkdf-memory=#::  Sets the memory cost for PBKDF. Only relevant if [option]#--encrypted# is also specified. See the `cryptsetup(8)` man page for more information.

[option]#pbkdf-time=#::  Sets the number of miliseconds to spend with PBKDF passphrase processing. Only relevant if [option]#--encrypted# is also specified. See information about the [option]#--iter-time# option in the `cryptsetup(8)` man page for more information.
+
Only one of [option]#--pbkdf-time=# or [option]#--pbkdf-iterations=# can be specified at the same time.

[option]#pbkdf-iterations=#::  Sets the number of iterations for passphrase processing directly, and avoids PBKDF benchmark. Only relevant if [option]#--encrypted# is also specified. See information about the [option]#--pbkdf-force-iterations# option in the `cryptsetup(8)` man page for more information.
+
Only one of [option]#--pbkdf-time=# or [option]#--pbkdf-iterations=# can be specified at the same time.

The following example shows how to create a RAID level 1 partition for `/`, and a RAID level 5 for `/home`, assuming there are three SCSI disks on the system. It also creates three swap partitions, one on each drive.

.Creating a RAID array in Kickstart
====

[subs="quotes, macros, attributes"]
----

[command]#part raid.01 --size=6000 --ondisk=sda#
[command]#part raid.02 --size=6000 --ondisk=sdb#
[command]#part raid.03 --size=6000 --ondisk=sdc#

[command]#part swap --size=512 --ondisk=sda#
[command]#part swap --size=512 --ondisk=sdb#
[command]#part swap --size=512 --ondisk=sdc#

[command]#part raid.11 --size=1 --grow --ondisk=sda#
[command]#part raid.12 --size=1 --grow --ondisk=sdb#
[command]#part raid.13 --size=1 --grow --ondisk=sdc#

[command]#raid / --level=1 --device=f{PRODVER}-root --label=f{PRODVER}-root raid.01 raid.02 raid.03#
[command]#raid /home --level=5 --device=f{PRODVER}-home --label=f{PRODVER}-home raid.11 raid.12 raid.13#

----

====

[[sect-kickstart-commands-reqpart]]
=== reqpart (optional) - Create Required Partitions

Automatically create partitions required by your hardware platform. These include a `/boot/efi` for x86_64 and Aarch64 systems with UEFI firmware, `biosboot` for x86_64 systems with BIOS firmware and GPT (GUID Partition Table), and `PRePBoot` for IBM Power Systems.

[NOTE]
====

This command can not be used together with [command]#autopart#, because [command]#autopart# does the same and creates other partitions or logical volumes such as `/` and `swap` on top. In contrast with [command]#autopart#, this command only creates platform-specific partitions and leaves the rest of the drive empty, allowing you to create a custom layout.

====

[subs="quotes, macros"]
----
[command]#reqpart [--add-boot]#
----

[option]#--add-boot#::  Create a separate `/boot` partition in addition to the platform-specific partition created by the base command.

[[sect-kickstart-commands-volgroup]]
=== volgroup (optional) - Create LVM Volume Group

Creates a Logical Volume Management (LVM) volume group.

[subs="quotes, macros"]
----
[command]#volgroup _name_ _partition_ [pass:attributes[{blank}]_options_pass:attributes[{blank}]]#
----

[IMPORTANT]
====

Do not use the dash (`-`) character in logical volume and volume group names when installing {PRODUCT} using Kickstart. If this character is used, the installation will finish normally, but the `/dev/mapper/` directory will list these volumes and volume groups with every dash doubled. For example, a volume group named `volgrp-01` containing a logical volume named `logvol-01` will be listed as `/dev/mapper/volgrp--01-logvol--01`.

This limitation only applies to newly created logical volume and volume group names. If you are reusing existing ones using the [option]#--noformat# or [option]#--noformat# option, their names will not be changed.

====

For a detailed partitioning example including [command]#volgroup#, see xref:sect-kickstart-example-advanced-partitioning[Advanced Partitioning Example].

[option]#--noformat#::  Use an existing volume group and do not format it.

[option]#--useexisting#::  Use an existing volume group and reformat it.

[option]#--pesize=#::  Set the size of the physical extents. The default size for Kickstart installations is 4 MiB.

[option]#--reserved-space=#::  Specify an amount of space to leave unused in a volume group in megabytes. Applicable only to newly created volume groups.

[option]#--reserved-percent=#::  Specify a percentage of total volume group space to leave unused. Applicable only to newly created volume groups.

Create one or more partitions first using xref:sect-kickstart-commands-part[part (required) - Create Physical Partition], create the logical volume group (xref:sect-kickstart-commands-volgroup[volgroup (optional) - Create LVM Volume Group]), and then create logical volumes. For example:

[subs="quotes, macros"]
----

[command]#part pv.01 --size 3000#
[command]#volgroup myvg pv.01#
[command]#logvol / --vgname=myvg --size=2000 --name=rootvol#

----

[[sect-kickstart-commands-zerombr]]
=== zerombr (optional) - Reinitialize Partition Tables

If [command]#zerombr# is specified, any invalid partition tables found on disks are initialized. This destroys all of the contents of disks with invalid partition tables. This command is required when performing an unattended installation on a system with previously initialized disks.

[WARNING]
====

On IBM System{nbsp}z, if [command]#zerombr# is specified, any _Direct Access Storage Device_ (DASD) visible to the installation program which is not already low-level formatted is automatically low-level formatted with [application]*dasdfmt*. The command also prevents user choice during interactive installations.

If [command]#zerombr# is not specified and there is at least one unformatted DASD visible to the installation program, a non-interactive Kickstart installation will exit unsuccessfully.

If [command]#zerombr# is not specified and there is at least one unformatted DASD visible to the installation program, an interactive installation exits if the user does not agree to format all visible and unformatted DASDs. To circumvent this, only activate those DASDs that you will use during installation. You can always add more DASDs after installation is complete.

====

[[sect-kickstart-commands-zfcp]]
=== zfcp (optional) - Configure Fibre Channel Device

Define a Fibre channel device. This option only applies on IBM System{nbsp}z. All of the options described below must be specified.

[subs="quotes, macros"]
----
[command]#zfcp --devnum=pass:attributes[{blank}]_devnum_ --wwpn=pass:attributes[{blank}]_wwpn_ --fcplun=pass:attributes[{blank}]_lun_pass:attributes[{blank}]#
----

[option]#--devnum#::  The device number (zFCP adaptor device bus ID).

[option]#--wwpn#::  The device's World Wide Port Name (WWPN). Takes the form of a 16-digit number, preceded by `0x`.

[option]#--fcplun#::  The device's Logical Unit Number (LUN). Takes the form of a 16-digit number, preceded by `0x`.

For example:

[subs="quotes, macros"]
----
[command]#zfcp --devnum=0.0.4000 --wwpn=0x5005076300C213e9 --fcplun=0x5022000000000000#
----

[[sect-kickstart-commands-network-configuration]]
== Network Configuration

Commands in this chapter are used for network configuration.

[[sect-kickstart-commands-firewall]]
=== firewall (optional) - Configure Firewall

Specify the firewall configuration for the installed system.

[subs="quotes, macros"]
----
[command]#firewall --enabled | --disabled _device_ [--trust= | --ssh | --smtp | --http | --ftp | --port= | --service=]#
----

[option]#--enabled# or [option]#--enable#::  Reject incoming connections that are not in response to outbound requests, such as DNS replies or DHCP requests. If access to services running on this machine is needed, you can choose to allow specific services through the firewall.

[option]#--disabled# or [option]#--disable#::  Disable the firewall.

[option]#--trust=#::  Listing a device here, such as `em1`, allows all traffic coming to and from that device to go through the firewall. To list more than one device, use this option again - for example:
+
[subs="quotes, macros"]
----
[command]#firewall --enable --trust=em1 --trust=em2#
----
+
Do not use a comma-separated format such as [option]#--trust em1, em2#.

_incoming_::  Replace with one or more of the following to allow the specified services through the firewall:
+
** [option]#--ssh#
+
** [option]#--smtp#
+
** [option]#--http#
+
** [option]#--ftp#

[option]#--port=#::  You can specify that ports be allowed through the firewall using the port:protocol format. For example, to allow IMAP access through your firewall, specify `imap:tcp`. Numeric ports can also be specified explicitly; for example, to allow UDP packets on port 1234 through, specify `1234:udp`. To specify multiple ports, separate them by commas.

[option]#--service=#::  This option provides a higher-level way to allow services through the firewall. Some services (like `cups`, `avahi`, etc.) require multiple ports to be open or other special configuration in order for the service to work. You can specify each individual port with the [option]#--port# option, or specify [command]#--service=# and open them all at once.
+
Valid options are anything recognized by the [application]*firewall-offline-cmd* program in the [package]*firewalld* package. If `firewalld` is running, [command]#firewall-cmd --get-services# will provide a list of known service names.

[[sect-kickstart-commands-network]]
=== network (optional) - Configure Network Interfaces

Configures network information for the target system and activates network devices in the installation environment. The device specified in the first [command]#network# command is activated automatically. Activation of the device can be also explicitly required by the [option]#--activate# option.

[option]#--activate#::  If you use the [option]#--activate# option on a device that has already been activated (for example, an interface you configured with boot options so that the system could retrieve the Kickstart file) the device is reactivated to use the details specified in the Kickstart file.
+
Use the [option]#--nodefroute# option to prevent the device from using the default route.

[option]#--no-activate#::  Prevents the configured device from automatically activating on boot.

[option]#--bootproto=#::  One of `dhcp`, `bootp`, `ibft`, or `static`. The default option is `dhcp`pass:attributes[{blank}]; the `dhcp` and `bootp` options are treated the same.
+
The DHCP method uses a DHCP server system to obtain its networking configuration. The BOOTP method is similar, requiring a BOOTP server to supply the networking configuration. To direct a system to use DHCP:
+
[subs="quotes, macros"]
----
[command]#network --bootproto=dhcp#
----
+
To direct a machine to use BOOTP to obtain its networking configuration, use the following line in the Kickstart file:
+
[subs="quotes, macros"]
----
[command]#network --bootproto=bootp#
----
+
To direct a machine to use the configuration specified in iBFT, use:
+
[subs="quotes, macros"]
----
[command]#network --bootproto=ibft#
----
+
The `static` method requires that you specify the IP address, netmask, gateway, and nameserver in the Kickstart file. This information is static and is used during and after the installation.
+
All static networking configuration information must be specified on *one* line; you cannot wrap lines using a backslash (`\`) as you can on a command line.
+
[subs="quotes, macros"]
----
[command]#network --bootproto=static --ip=10.0.2.15 --netmask=255.255.255.0 --gateway=10.0.2.254 --nameserver=10.0.2.1#
----
+
You can also configure multiple nameservers at the same time. To do so, use the [option]#--nameserver=# options once for each name server you want to configure:
+
[subs="quotes, macros"]
----
[command]#network --bootproto=static --ip=10.0.2.15 --netmask=255.255.255.0 --gateway=10.0.2.254 --nameserver=192.168.2.1 --nameserver=192.168.3.1#
----

[option]#--device=#::  Specifies the device to be configured (and eventually activated in [application]*Anaconda*) with the [command]#network# command.
+
If the [option]#--device=# option is missing on the *first* use of the [command]#network# command, the value of the [option]#ksdevice=# [application]*Anaconda* boot option is used, if available. Note that this is considered deprecated behavior; in most cases, you should always specify a [option]#--device=# for every [command]#network# command.
+
The behavior of any subsequent [command]#network# command in the same Kickstart file is unspecified if its [option]#--device=# option is missing. Make sure you specify this option for any [command]#network# command beyond the first.
+
You can specify a device to be activated in any of the following ways:
+
** the device name of the interface, for example, `em1`
+
** the MAC address of the interface, for example, `01:23:45:67:89:ab`
+
** the keyword `link`, which specifies the first interface with its link in the `up` state
+
** the keyword `bootif`, which uses the MAC address that [application]*pxelinux* set in the `BOOTIF` variable. Set `IPAPPEND 2` in your `pxelinux.cfg` file to have [application]*pxelinux* set the `BOOTIF` variable.
+
For example:
+
[subs="quotes, macros"]
----
[command]#network --bootproto=dhcp --device=em1#
----

[option]#--bindto=#::  Optional. Allows to specify how the connection configuration created for the device should be bound. If the option is not used, the connection binds to interface name (`DEVICE` value in ifcfg file). For virtual devices (bond, team, bridge) it configures binding of slaves. Not applicable to vlan devices.
+
Note that this option is independent of how the `--device` is specified.
+
Currently only the value `mac` is suported. `--bindto=mac` will bind  the connection to MAC address of the device (`HWADDR` value in the `ifcfg` file).
+
For example:
+
[subs="quotes, macros"]
----
[command]#network --device=01:23:45:67:89:ab --bootproto=dhcp --bindto=mac#
----
+
The above will bind the configuration of the device specified by MAC address `01:23:45:67:89:ab` to its MAC address.
+
[subs="quotes, macros"]
----
network --device=01:23:45:67:89:ab --bootproto=dhcp
----
The above will bind the configuration of the device specified by MAC address `01:23:45:67:89:ab` to its interface name (e.g. `ens3`).
+
[subs="quotes, macros"]
----
[command]#network --device=ens3 --bootproto=dhcp --bindto=mac#
----
+
The above will bind the configuration of the device specified by interface name `ens3` to its MAC address.

[option]#--ip=#::  IP address of the device.

[option]#--ipv6=#::  IPv6 address of the device, in the form of _address_pass:attributes[{blank}][/pass:attributes[{blank}]_prefix_ _length_pass:attributes[{blank}]] - for example, `3ffe:ffff:0:1::1/128` . If _prefix_ is omitted, `64` will be used. You can also use `auto` for automatic configuration, or `dhcp` for DHCPv6-only configuration (no router advertisements).

[option]#--gateway=#::  Default gateway as a single IPv4 address.

[option]#--ipv6gateway=#::  Default gateway as a single IPv6 address.

[option]#--nodefroute#::  Prevents the interface being set as the default route. Use this option when you activate additional devices with the [option]#--activate=# option, for example, a NIC on a separate subnet for an iSCSI target.

[option]#--nameserver=#::  DNS name server, as an IP address. To specify more than one name server, use this parameter multiple times. For example:
+
[subs="quotes, macros"]
----
[command]#network --bootproto=static --ip=10.0.2.15 --netmask=255.255.255.0 --gateway=10.0.2.254 --nameserver=192.168.2.1 --nameserver=192.168.3.1#
----

[option]#--nodns#::  Do not configure any DNS server.

[option]#--netmask=#::  Network mask for the installed system.

[option]#--hostname=#::  Host name for the installed system. The host name can be either a _fully-qualified domain name_ (FQDN) in the format _hostname_._domainname_, or a short host name with no domain name. Many networks have a _Dynamic Host Configuration Protocol_ (`DHCP`) service that automatically supplies connected systems with a domain name; to allow the `DHCP` service to assign the domain name to this machine, only specify the short host name.

[option]#--ethtool=#::  Specifies additional low-level settings for the network device which will be passed to the [application]*ethtool* program.

[option]#--essid=#::  The network ID for wireless networks.

[option]#--wepkey=#::  The WEP encryption key for wireless networks.

[option]#--wpakey=#::  The WPA encryption key for wireless networks.

[option]#--onboot=#::  Whether or not to enable the device at boot time.

[option]#--dhcpclass=#::  The DHCP class.

[option]#--mtu=#::  The MTU of the device.

[option]#--noipv4#::  Disable IPv4 on this device.

[option]#--noipv6#::  Disable IPv6 on this device.

[option]#--bondslaves=#::  When this option is used, the network device specified in the [option]#--device=# option will be created using slaves defined in the [option]#--bondslaves=# option. For example:
+
[subs="quotes, macros"]
----
[command]#network --device=mynetwork --bondslaves=em1,em2#
----
+
The above command will create a bond device named `mynetwork` using the `em1` and `em2` interfaces as its slaves.

[command]#--bondopts=#::  A list of optional parameters for a bonded interface, which is specified using the [command]#--bondslaves=# and [command]#--device=# options. Options in this list must be separated by commas ("pass:attributes[{blank}]`,`pass:attributes[{blank}]") or semicolons ("pass:attributes[{blank}]`;`pass:attributes[{blank}]"). If an option itself contains a comma, use a semicolon to separate the options. For example:
+
[subs="quotes, macros"]
----
[command]#network --bondopts=mode=active-backup,balance-rr;primary=eth1#
----
+
Available optional parameters are listed in the [citetitle]_Working with Kernel Modules_ chapter of the [citetitle]_Fedora System Administrator's Guide_, available at link:++https://docs.fedoraproject.org/++[].
+
[IMPORTANT]
====

The [option]#--bondopts=mode=# parameter only supports full mode names such as `balance-rr` or `broadcast`, not their numerical representations such as `0` or `3`.

====

[option]#--vlanid=#::  Specifies virtual LAN (VLAN) ID number (802.1q tag) for the device created using the device specified in [option]#--device=# as a parent. For example, [command]#network --device=em1 --vlanid=171# will create a virtual LAN device `em1.171`.

[option]#--interfacename=#::  Specify a custom interface name for a virtual LAN device. This option should be used when the default name generated by the [option]#--vlanid=# option is not desirable. This option must be used along with [option]#--vlanid=#. For example:
+
[subs="quotes, macros"]
----
[command]#network --device=em1 --vlanid=171 --interfacename=vlan171#
----
+
The above command will create a virtual LAN interface named `vlan171` on the `em1` device with an ID of `171`.
+
The interface name can be arbitrary (for example, `my-vlan`), but in specific cases, the following conventions must be followed:
+
** If the name contains a dot (`.`), it must take the form of `pass:attributes[{blank}]_NAME_._ID_pass:attributes[{blank}]`. The _NAME_ is arbitrary, but the _ID_ must be the VLAN ID. For example: `em1.171` or `my-vlan.171`.
+
** Names starting with `vlan` must take the form of `vlanpass:attributes[{blank}]_ID_pass:attributes[{blank}]` - for example, `vlan171`.

[option]#--teamslaves=#::  Team device specified by the [option]#--device=# option will be created using slaves specified in this option. Slaves are separated by commas. A slave can be followed by its configuration, which is a single-quoted JSON string with double quotes escaped by the `\` character. For example:
+
[subs="quotes, macros"]
----
[command]#network --teamslaves="p3p1'{\"prio\": -10, \"sticky\": true}',p3p2'{\"prio\": 100}'"#
----
+
See also the [option]#--teamconfig=# option.

[option]#--teamconfig=#::  Double-quoted team device configuration which is a single-quoted JSON string with double quotes escaped by the `\` character. The device name is specified by [option]#--device=# option and its slaves and their configuration by [option]#--teamslaves=# option. For example:
+
[subs="quotes, macros"]
----

[command]#network --device team0 --activate --bootproto static --ip=10.34.102.222 --netmask=255.255.255.0 --gateway=10.34.102.254 --nameserver=10.34.39.2 --teamslaves="p3p1'{\"prio\": -10, \"sticky\": true}',p3p2'{\"prio\": 100}'" --teamconfig="{\"runner\": {\"name\": \"activebackup\"}}"#

----

[option]#--bridgeslaves=#::  When this option is used, the network bridge with device name specified using the [option]#--device=# option will be created and devices defined in the [option]#--bridgeslaves=# option will be added to the bridge. For example:
+
[subs="quotes, macros"]
----
[command]#network --device=bridge0 --bridgeslaves=em1#
----

[option]#--bridgeopts=#::  An optional comma-separated list of parameters for the bridged interface. Available values are `stp`, `priority`, `forward-delay`, `hello-time`, `max-age`, and `ageing-time`. For information about these parameters, see the [citetitle]_bridge setting_ table in the `nm-settings(5)` man page or at link:++https://developer.gnome.org/NetworkManager/0.9/ref-settings.html++[]. Also see the [citetitle]_{PRODUCT} Networking Guide_, available at link:++https://docs.fedoraproject.org/++[], for general information about network bridging.

[[sect-kickstart-commands-environment]]
== Console and Environment

The following commands control the environment of the system after the installation finishes - language, keyboard layouts, or the graphical interface.

[[sect-kickstart-commands-keyboard]]
=== keyboard (optional) - Configure Keyboard Layouts

Sets one or more available keyboard layouts for the system.

[subs="quotes, macros"]
----
[command]#keyboard --vckeymap= | --xlayouts= [--switch=]#
----

[option]#--vckeymap=#::  Specify a `VConsole` keymap which should be used. Valid names correspond to the list of files in the `/usr/lib/kbd/keymaps/*` directory, without the `.map.gz` extension.

[option]#--xlayouts=#::  Specify a list of [application]*X* layouts that should be used as a comma-separated list without spaces. Accepts values in the same format as `setxkbmap(1)`, either in the `pass:attributes[{blank}]_layout_pass:attributes[{blank}]` format (such as `cz`), or in the `pass:attributes[{blank}]_layout_ (_variant_)` format (such as `cz (qwerty)`).
+
All available layouts can be viewed on the `xkeyboard-config(7)` man page under `Layouts`.

[option]#--switch=#::  Specify a list of layout-switching options (shortcuts for switching between multiple keyboard layouts). Multiple options must be separated by commas without spaces. Accepts values in the same format as `setxkbmap(1)`.
+
Available switching options can be viewed on the `xkeyboard-config(7)` man page under `Options`.

The following example sets up two keyboard layouts (`English (US)` and `Czech (qwerty)`) using the [option]#--xlayouts=# option, and allows to switch between them using kbd:[Alt + Shift]:

----
keyboard --xlayouts=us,'cz (qwerty)' --switch=grp:alt_shift_toggle
----

[[sect-kickstart-commands-lang]]
=== lang (optional) - Configure Language During Installation

Sets the language to use during installation and the default language to use on the installed system.

[subs="quotes, macros"]
----
[command]#lang _language_ [--addsupport=]#
----

The file `/usr/share/system-config-language/locale-list` provides a list of the valid _language_ codes in the first column of each line and is part of the [package]*system-config-language* package.

Certain languages (for example, Chinese, Japanese, Korean, and Indic languages) are not supported during text-mode installation. If you specify one of these languages with the [command]#lang# command and use text mode, the installation process will continue in English, but the installed system will use your selection as its default language.

[option]#--addsupport=#::  Add support for additional languages. Takes the form of comma-separated list without spaces. For example:
+
----
lang en_US --addsupport=cs_CZ,de_DE,en_UK
----

[[sect-kickstart-commands-services]]
=== services (optional) - Configure Services

Modifies the default set of services that will run under the default [application]*systemd* target. The list of disabled services is processed before the list of enabled services - therefore, if a service appears on both lists, it will be enabled.

[subs="quotes, macros"]
----
[command]#services [--disabled=pass:attributes[{blank}]_list_pass:attributes[{blank}]] [--enabled=pass:attributes[{blank}]_list_pass:attributes[{blank}]]#
----

Do not include spaces in the list of services. If you do, Kickstart will enable or disable only the services up to the first space. For example:

[subs="quotes, macros"]
----
[command]#services --disabled=auditd, cups,smartd, nfslock#
----

The above will disable only the `auditd` service. To disable all four services, the entry should include no spaces:

[subs="quotes, macros"]
----
[command]#services --disabled=auditd,cups,smartd,nfslock#
----

[option]#--disabled=#::  Disable the services given in the comma separated list.

[option]#--enabled=#::  Enable the services given in the comma separated list.

[[sect-kickstart-commands-skipx]]
=== skipx (optional) - Do Not Configure X Window System

If present, [application]*X* will not be configured on the installed system.

[IMPORTANT]
====

If you install a display manager among your package selection options, this package will create an [application]*X* configuration, and the installed system will default to `graphical.target`. The effect of the [command]#skipx# option will be overridden.

====

[[sect-kickstart-commands-timezone]]
=== timezone (optional) - Configure Time Zone

Sets the system time zone to _timezone_. To view a list of available time zones, use the [command]#timedatectl list-timezones# command.

Every option, including actually specifying a time zone, is optional starting with Fedora 25. This allows you to, for example, disable NTP from starting using [option]#--nontp# without having to choose any time zone. However, if this command is present in the Kickstart file, at least one option must be used.

[subs="quotes, macros"]
----
[command]#timezone [pass:attributes[{blank}]_timezone_pass:attributes[{blank}]] [pass:attributes[{blank}]_options_pass:attributes[{blank}]]#
----

[option]#--utc#::  If present, the system assumes the hardware clock is set to UTC (Greenwich Mean) time.

[option]#--nontp#::  Disable the NTP service automatic starting.

[option]#--ntpservers=#::  Specify a list of NTP servers to be used as a comma-separated list without spaces.

[[sect-kickstart-commands-xconfig]]
=== xconfig (optional) - Configure X Window System

Configures the [application]*X Window System*. If you install the [application]*X Window System* with a Kickstart file that does not include the [command]#xconfig# command, you must provide the [application]*X* configuration manually during installation.

Do not use this command in a Kickstart file that does not install the [application]*X Window System*.

[option]#--defaultdesktop=#::  Specify either `GNOME` or `KDE` to set the default desktop (assumes that [application]*GNOME Desktop Environment* and/or [application]*KDE Desktop Environment* has been installed in the [command]#%packages# section).

[option]#--startxonboot#::  Use a graphical login on the installed system.

[[sect-kickstart-commands-users-groups]]
== Users, Groups and Authentication

The commands below are used to control user accounts, groups, and related areas.

[[sect-kickstart-commands-authconfig]]
=== auth or authconfig (optional) - Configure Authentication (deprecated)

[IMPORTANT]
====
This command has been deprecated by [command]#authselect#. Using it will invoke the authconfig compatibility tool; however, it is highly recommended to use [command]#authselect# instead.
====

Sets up the authentication options for the system using the [command]#authconfig# command, which can also be run on a command line after the installation finishes. See the `authconfig(8)` manual page and the [command]#authconfig --help# command for more details. Passwords are shadowed by default.

[[sect-kickstart-commands-authselect]]
=== authselect (optional) - Configure Authentication

This command sets up the authentication options for the system. This is just a wrapper around the [command]#authselect# program, so all options recognized by that program are valid for this command. See the `authselect(8)` for a complete list. Passwords are shadowed by default.


[[sect-kickstart-commands-group]]
=== group (optional) - Create User Group

Creates a new user group on the system. If a group with the given name or GID already exists, this command will fail. In addition, the [command]#user# command can be used to create a new group for the newly created user.

[subs="quotes, macros"]
----
[command]#group --name=pass:attributes[{blank}]_name_ [--gid=pass:attributes[{blank}]_gid_pass:attributes[{blank}]]#
----

[option]#--name=#::  Provides the name of the group.

[option]#--gid=#::  The group ID (GID). If not provided, defaults to the next available non-system GID.

[[sect-kickstart-commands-pwpolicy]]
=== pwpolicy (optional) - Change the Default Password Policy

This command can be used to set custom requirements (policy) such as length and strength for passwords set during the installation - the `root` password, user passwords and LUKS (disk encryption) password.

[subs="quotes, macros"]
----

[command]#pwpolicy _name_ [--minlen=pass:attributes[{blank}]_length_pass:attributes[{blank}]] [--minquality=pass:attributes[{blank}]_quality_pass:attributes[{blank}]] [--strict|nostrict] [--emptyok|noempty] [--changesok|nochanges]#

----

The `libpwquality` library is used to check minimum password requirements (length and quality). You can use the [command]#pwscore# and [command]#pwmake# commands provided by the [package]*libpwquality* package to check the quality score of your chosen password, or to create a random password with a given score. See the `pwscore(1)` and `pwmake(1)` man pages for details about these commands.

[IMPORTANT]
====

This command must be used inside the [command]#%anaconda# section. See xref:sect-kickstart-commands-anaconda[%anaconda (optional) - Additional Anaconda Configuration] for details.

====

_name_::  Name of the password entry. Supported values are `root`, `user` and `luks` for `root` password, user passwords and LUKS password, respectively.

[option]#--minlen=#::  Sets the minimum allowed password length. The default minimum length is `8`.

[option]#--minquality=#::  Sets the minimum allowed password quality as defined by the `libpwquality` library. The default value is `50`.

[option]#--strict#::  Strict password enforcement. Passwords not meeting the quality requirements specified in [option]#--minquality=# will not be allowed. Enabled by default.

[option]#--notstrict#::  Passwords *not* meeting the minimum quality requirements specified in [option]#--minquality=# will be allowed after `Done` is clicked twice.

[option]#--emptyok#::  Allow empty passwords. Enabled by default.

[option]#--notempty#::  Do not allow empty passwords.

[option]#--changesok#::  Allow changing the password in the user interface, even if the Kickstart file already specifies a password.

[option]#--nochanges#::  Do not allow changing passwords which are already set in the Kickstart file. Enabled by default.

An example use of the [command]#pwpolicy# command is below:

[subs="quotes, macros"]
----

[command]#%anaconda#
[command]#pwpolicy root --minlen=10 --minquality=60 --strict --notempty --nochanges#
[command]#%end#

----

[[sect-kickstart-commands-realm]]
=== realm (optional) - Join an Active Directory or IPA Domain

Join an Active Directory or IPA domain. For more information about this command, see the [command]#join# section of the `realm(8)` man page.

[subs="quotes, macros"]
----
[command]#realm join _domain_ [pass:attributes[{blank}]_options_pass:attributes[{blank}]]#
----

[option]#--computer-ou=OU=#::  Provide the _distinguished name_ of an organizational unit in order to create the computer account. The exact format of the distinguished name depends on the client software and membership software. The root DSE portion of the distinguished name can usually be left out.

[option]#--no-password#::  Join automatically without a password.

[option]#--one-time-password=#::  Join using a one-time password. This is not possible with all types of realm.

[option]#--client-software=#::  Only join realms which can run this client software. Valid values include `sssd` and `winbind`. Not all realms support all values. By default, the client software is chosen automatically.

[option]#--server-software=#::  Only join realms which can run this server software. Possible values include `active-directory` or `freeipa`.

[option]#--membership-software=#::  Use this software when joining the realm. Valid values include `samba` and `adcli`. Not all realms support all values. By default, the membership software is chosen automatically.

[[sect-kickstart-commands-rootpw]]
=== rootpw (required) - Set Root Password

Sets the system's root password to the _password_ argument.

[subs="quotes, macros"]
----
[command]#rootpw [--iscrypted|--plaintext] [--lock] _password_pass:attributes[{blank}]#
----

[option]#--iscrypted#::  If this option is present, the password argument is assumed to already be encrypted. This option is mutually exclusive with [option]#--plaintext#. To create an encrypted password, you can use Python:
+
[subs="quotes, macros"]
----
$ [command]#python -c 'import crypt; print(crypt.crypt("My Password", "$6$My Salt"))'#
----
+
This will generate a SHA512 crypt of your password using your provided salt.

[option]#--plaintext#::  If this option is present, the password argument is assumed to be in plain text. This option is mutually exclusive with [option]#--iscrypted#.

[option]#--lock#::  If this option is present, the root account is locked by default. This means that the root user will not be able to log in from the console.

[[sect-kickstart-commands-selinux]]
=== selinux (optional) - Configure SELinux

Sets the state of SELinux on the installed system. The default policy is `enforcing`. For more information regarding SELinux in {PRODUCT}, see the [citetitle]_{PRODUCT} SELinux User's and Administrator's Guide_, available at link:++https://docs.fedoraproject.org/++[].

[subs="quotes, macros"]
----
[command]#selinux [--disabled|--enforcing|--permissive]#
----

[option]#--enforcing#::  Enables SELinux with the default targeted policy being `enforcing`.

[option]#--permissive#::  Enables SELinux with the default targeted policy being `permissive`. This policy outputs warnings based on the SELinux policy, but does not actually enforce the policy.

[option]#--disabled#::  Disables SELinux completely.

[[sect-kickstart-commands-sshkey]]
=== sshkey (optional) - Add an Authorized SSH Key

Use this command to add a specified `SSH` key to an user's `authorized_keys` file. The specified user must either be `root`, or it must be created in the Kickstart file - either automatically by an installed package, or using xref:sect-kickstart-commands-user[user (optional) - Create User Account].

----
sshkey --username=user "ssh_key"
----

The _ssh_key_ must be a full `SSH` key fingerprint, and it must be enclosed in quotes (`""`) because the key may contain spaces.

[option]#--username=#::  The name of the user account to which you want to install the `SSH` key.

[[sect-kickstart-commands-user]]
=== user (optional) - Create User Account

Creates a new user on the system.

[subs="quotes, macros"]
----
[command]#user --name=pass:attributes[{blank}]_username_ [pass:attributes[{blank}]_options_pass:attributes[{blank}]]#
----

[option]#--name=#::  Provides the name of the user. This option is required.

[option]#--gecos=#::  Provides the GECOS information for the user. This is a string of various system-specific fields separated by a comma. It is frequently used to specify the user's full name, office number, etc. See the `passwd(5)` man page for more details.

[option]#--groups=#::  In addition to the default group, a comma separated list of group names the user should belong to. The groups must exist before the user account is created. See xref:sect-kickstart-commands-group[group (optional) - Create User Group].

[option]#--homedir=#::  The home directory for the user. If not provided, this defaults to `/home/pass:attributes[{blank}]_username_pass:attributes[{blank}]`.

[option]#--lock#::  If this option is present, this account is locked by default. This means that the user will not be able to log in from the console.

[option]#--password=#::  The new user's password. If no password is provided, the account will be locked.

[option]#--iscrypted#::  If this option is present, the password argument is assumed to already be encrypted. This option is mutually exclusive with [option]#--plaintext#. To create an encrypted password, you can use Python:
+
[subs="quotes, macros"]
----
$ [command]#python -c 'import crypt; print(crypt.crypt("My Password", "$6$My Salt"))'#
----
+
This will generate a SHA512 crypt of your password using your provided salt.

[option]#--plaintext#::  If this option is present, the password argument is assumed to be in plain text. This option is mutually exclusive with [option]#--iscrypted#.

[option]#--shell=#::  The user's login shell. If not provided, the system default will be used.

[option]#--uid=#::  The _UID_ (User ID). If not provided, this defaults to the next available non-system UID.

[option]#--gid=#::  The _GID_ (Group ID) to be used for the user's default group. If not provided, this defaults to the next available non-system group ID.

[[sect-kickstart-commands-installation-environment]]
== Installation Environment

The following commands control how the system will behave during the installation.

[[sect-kickstart-commands-autostep]]
=== autostep (optional) - Go Through Every Screen

Normally, Kickstart installations skip unnecessary screens. This option makes the installation program step through every screen, displaying each briefly. This option should not be used when deploying a system because it may disrupt package installation.

[subs="quotes, macros"]
----
[command]#autostep [--autoscreenshot]#
----

[option]#--autoscreenshot#::  Take a screenshot at every step during installation. These screenshots are stored in `/tmp/anaconda-screenshots` during the installation, and after the installation finishes you can find them in `/root/anaconda-screenshots`.
+
Each screen is only captured right before the installer switches to the next one. This is important, because if you do not use all required Kickstart options and the installation therefore does not begin automatically, you can go to the screens which were not automatically configured, perform any configuration you want. Then, when you press `Done` to continue, the screen will be captured including the configuration you just provided.

[[sect-kickstart-commands-cmdline]]
=== cmdline (optional) - Perform Installation in Command Line Mode

Perform the installation in a completely non-interactive command line mode. Any prompts for interaction halts the install. This mode is useful on IBM System{nbsp}z systems with the x3270 terminal.

[IMPORTANT]
====

For a fully automatic installation, you must either specify one of the available modes ([command]#graphical#, [command]#text#, or [command]#cmdline#) in the Kickstart file, or you must use the [option]#console=# boot option as described in xref:advanced/Boot_Options.adoc#sect-boot-options-display[Console, Environment and Display Options]. Otherwise the system will halt and ask you to choose a mode.

====

[[sect-kickstart-commands-graphical]]
=== graphical (optional) - Perform Installation in Graphical Mode

Perform the installation in graphical mode. This is the default. This command takes no options.

[IMPORTANT]
====

For a fully automatic installation, you must either specify one of the available modes ([command]#graphical#, [command]#text#, or [command]#cmdline#) in the Kickstart file, or you must use the [option]#console=# boot option as described in xref:advanced/Boot_Options.adoc#sect-boot-options-display[Console, Environment and Display Options]. Otherwise the system will halt and ask you to choose a mode.

====

[[sect-kickstart-commands-logging]]
=== logging (optional) - Configure Error Logging During Installation

Controls the error logging of [application]*Anaconda* during installation. It has no effect on the installed system.

[subs="quotes, macros"]
----
[command]#logging [--host= | --port= | --level=]#
----

[option]#--host=#::  Send logging information to the given remote host, which must be running a `syslogd` process configured to accept remote logging.

[option]#--port=#::  If the remote syslogd process uses a port other than the default, it may be specified with this option.

[option]#--level=#::  Specify the minimum level of messages that appear on virtual console 3 (`tty3`). This only affects messages printed to the console; log files will contain messages of all levels. Possible values are `debug`, `info`, `warning`, `error`, or `critical`.

[[sect-kickstart-commands-rescue]]
=== rescue (optional) - Rescue Mode

Automatically enters the installation program's rescue mode. This gives you a chance to repair the system in case of any problems.

[subs="quotes, macros"]
----
[command]#rescue [--nomount|--romount]#
----

[option]#--nomount# or [option]#--romount#::  Controls how the installed system is mounted in the rescue environment. By default, the installation program will find your system and mount it in read-write mode, telling you where it has performed this mount. You may optionally choose to not mount anything (the [option]#--nomount# option) or mount in read-only mode (the [option]#--romount# option). Only one of these two options may be used.

[[sect-kickstart-commands-sshpw]]
=== sshpw (optional) - Restrict ssh Access During Installation

During the installation, you can interact with the installation program and monitor its progress over an `SSH` connection. Use the [command]#sshpw# command to create temporary accounts through which to log on. Each instance of the command creates a separate account that exists only in the installation environment. These accounts are not transferred to the installed system.

[subs="quotes, macros"]
----
[command]#sshpw --username=pass:attributes[{blank}]_name_ _password_ [--iscrypted|--plaintext] [--lock]#
----

[IMPORTANT]
====

By default, the `ssh` server is not started during the installation. To make `ssh` available during the installation, boot the system with the kernel boot option [option]#inst.sshd#. See xref:advanced/Boot_Options.adoc#sect-boot-options-display[Console, Environment and Display Options] for details.

====

[NOTE]
====

If you want to disable root `ssh` access to your hardware during installation, use the following:

[subs="quotes, macros"]
----
[command]#sshpw --username=root --lock#
----

====

[option]#--username#::  Provides the name of the user. This option is required.

[option]#--iscrypted#::  If this option is present, the password argument is assumed to already be encrypted. This option is mutually exclusive with [option]#--plaintext#. To create an encrypted password, you can use Python:
+
[subs="quotes, macros"]
----
$ [command]#python -c 'import crypt; print(crypt.crypt("My Password", "$6$My Salt"))'#
----
+
This will generate a SHA512 crypt of your password using your provided salt.

[option]#--plaintext#::  If this option is present, the password argument is assumed to be in plain text. This option is mutually exclusive with [option]#--iscrypted#

[option]#--lock#::  If this option is present, this account is locked by default. This means that the user will not be able to log in from the console.

[[sect-kickstart-commands-text]]
=== text (optional) - Perform Installation in Text Mode

Perform the Kickstart installation in text mode. Kickstart installations are performed in graphical mode by default.

[IMPORTANT]
====

For a fully automatic installation, you must either specify one of the available modes ([command]#graphical#, [command]#text#, or [command]#cmdline#) in the Kickstart file, or you must use the [option]#console=# boot option as described in xref:advanced/Boot_Options.adoc#sect-boot-options-display[Console, Environment and Display Options]. Otherwise the system will halt and ask you to choose a mode.

====

[[sect-kickstart-commands-unsupported_hardware]]
=== unsupported_hardware (optional) - Suppress Unsupported Hardware Alerts

Suppress the `Unsupported Hardware Detected` alert. If this command is not included and unsupported hardware is detected, the installation will stall at this alert.

[[sect-kickstart-commands-vnc]]
=== vnc (optional) - Configure VNC Access

Allows the graphical installation to be viewed remotely via VNC. This method is usually preferred over text mode, as there are some size and language limitations in text installations. With no additional options, this command will start a VNC server on the installation system with no password and will display the details required to connect to it.

[subs="quotes, macros"]
----
[command]#vnc [--host=pass:attributes[{blank}]_hostname_pass:attributes[{blank}]] [--port=pass:attributes[{blank}]_port_pass:attributes[{blank}]] [--password=pass:attributes[{blank}]_password_pass:attributes[{blank}]]#
----

For more information about VNC installations, including instructions on how to connect to the installation system, see xref:advanced/VNC_Installations.adoc#chap-vnc-installations[Installing Using VNC].

[option]#--host=#::  Connect to a VNC viewer listening on the given hostname.

[option]#--port=#::  Provide a port that the remote VNC viewer process is listening on. If not provided, the VNC default (`5900`) will be used.

[option]#--password=#::  Set a password which must be provided to connect to the VNC session. This is optional, but recommended.

[[sect-kickstart-commands-after]]
== After the Installation

This section contains commands which control the system's behavior immediately after the installation finishes.

[[sect-kickstart-commands-kdump]]
=== %addon com_redhat_kdump (optional) - Configure kdump

This command configures the [application]*kdump* kernel crash dumping mechanism.

[NOTE]
====

The syntax for this command is unusual because it is an add-on rather than a built-in Kickstart command. For more information about add-ons, see xref:sect-kickstart-commands-addon[%addon (optional) - Include an Anaconda Add-on].

====

[application]*Kdump* is a kernel crash dumping mechanism that allows you to save the contents of the system's memory for later analysis. It relies on [application]*kexec*, which can be used to start a Linux kernel from the context of another kernel without rebooting the system and preserve the contents of the first kernel memory that would otherwise be lost.

In case of a system crash, [application]*kexec* starts a second kernel (a _capture kernel_). This capture kernel resides in a reserved part of the system memory that is inaccessible to the main kernel. [application]*Kdump* then captures the contents of the crashed kernel's memory (a _crash dump_) and saves it to a specified location. This location can not be configured using Kickstart; it must be specified after the installation by editing the `/etc/kdump.conf` configuration file.

Available options are:

[option]#--enable#::  Enable [application]*Kdump* on the installed system.

[option]#--disable#::  Do not enable [application]*Kdump* on the installed system.

[option]#--reserve-mb=#::  The amount of memory you want to reserve for [application]*Kdump* in megabytes. For example:
+
----
%addon com_redhat_kdump --enable --reserve-mb=128
%end
----
+
You can also specify `auto` instead of a numeric value. In that case the installer will determine the amount of RAM to reserve for kdump automatically, based on your system architecture and the total amount of memory on the system.
+
If you enable [application]*Kdump* and do not specify the [option]#--reserve-mb=# option, the `auto` value will be used.

[option]#--enablefadump#::  Enable firmware-assisted dumping on systems which allow it (notably IBM Power{nbsp}Systems servers).

[[sect-kickstart-commands-firstboot]]
=== firstboot (optional) - Enable or Disable Initial Setup

Determine whether the [application]*Initial Setup* application starts the first time the system is booted. If enabled, the [package]*initial-setup* package must be installed. If not specified, this option is disabled by default. For more information about [application]*Initial Setup*, see xref:install/After_Installation.adoc#sect-initial-setup[Initial Setup].

[subs="quotes, macros"]
----
[command]#firstboot --enable|--disable [--reconfig]#
----

[option]#--enable# or [option]#--enabled#::  [application]*Initial Setup* will be started the first time the installed system boots.

[option]#--disable# or [option]#--disabled#::  [application]*Initial Setup* will be disabled.

[option]#--reconfig#::  [application]*Initial Setup* will start after the reboot in reconfiguration mode. This mode enables the language, mouse, keyboard, root password, security level, time zone and networking configuration options in addition to the default ones.

[[sect-kickstart-commands-halt]]
=== halt (optional) - Halt System After Installation

Halt the system after the installation has successfully completed. This is similar to a manual installation, where after the installation finishes, the installer displays a message and waits for the user to press a key before rebooting. During a Kickstart installation, if no completion method is specified, this option is used as the default.

For other completion methods, see the [command]#poweroff#, [command]#reboot#, and [command]#shutdown# commands.

[[sect-kickstart-commands-poweroff]]
=== poweroff (optional) - Power Off After Installation

Shut down and power off the system after the installation has successfully completed.

[NOTE]
====

The [command]#poweroff# command is highly dependent on the system hardware in use. Specifically, certain hardware components such as the BIOS, APM (advanced power management), and ACPI (advanced configuration and power interface) must be able to interact with the system kernel. Consult your hardware documentation for more information on you system's APM/ACPI abilities.

====

For other completion methods, see the [command]#halt#, [command]#reboot#, and [command]#shutdown# Kickstart commands.

[[sect-kickstart-commands-reboot]]
=== reboot (optional) - Reboot After Installation

Reboot after the installation is successfully completed. If you are installing {PRODUCT} on IBM System{nbsp}z in command line mode (using xref:sect-kickstart-commands-cmdline[cmdline (optional) - Perform Installation in Command Line Mode]), this command is necessary for a fully automated installation.

For other completion methods, see the [command]#halt#, [command]#poweroff#, and [command]#shutdown# Kickstart options.

[IMPORTANT]
====

Use of the [command]#reboot# command *may* result in an endless installation loop, depending on the installation media and method.

====

[option]#--eject#::  Attempt to eject the installation media (if installing from a DVD) before rebooting.

[option]#--kexec#::  Use this option to reboot into the new system using the `kexec` kernel switching mechanism instead of a full reboot, bypassing the BIOS/Firmware and boot loader.

[[sect-kickstart-commands-shutdown]]
=== shutdown (optional) - Shut Down After Installation

Shut down the system after the installation has successfully completed.

For other completion methods, see the [command]#halt#, [command]#poweroff#, and [command]#reboot# Kickstart options.

[[sect-kickstart-commands-addon]]
==== %addon (optional) - Include an Anaconda Add-on

You can expand the basic [application]*Anaconda* and Kickstart functionality by using custom add-ons specified using the [command]#%addon# section.

To use an add-on in your Kickstart file, add the [command]#%addon _addon_name_ _options_pass:attributes[{blank}]# command. The section must be closed with an [command]#%end# statement. For example, to use the [application]*Kdump* add-on, which is included by default on some installations, use the following block:

----
%addon com_redhat_kdump --enable --reserve-mb=128%end

----

The [command]#%addon# section does not have any options of its own; all options depend on the add-on being used.

For more information about [application]*Anaconda* add-ons, see the link:++https://vpodzime.fedorapeople.org/anaconda-addon-development-guide/++[Fedora Anaconda Addon Development Guide].

[[sect-kickstart-commands-anaconda]]
==== %anaconda (optional) - Additional Anaconda Configuration

This section, introduced in {PRODUCT} 22, is used to specify additional configuration options for the installer. Commands inside this section only control the behavior during installation, not on the installed system. The only command currently available inside this section is xref:sect-kickstart-commands-pwpolicy[pwpolicy (optional) - Change the Default Password Policy]. The [command]#%anaconda# section must end with `%end`.

In interactive installations (using the graphical or text interface), the `/usr/share/anaconda/interactive-defaults.ks` file contains the default [command]#%anaconda# section. To change the defaults, you must create a `product.img` file with a Kickstart file replacing the default one, and pass this file to [application]*Anaconda* using a boot option.

When using a Kickstart file, you can override the default [command]#%anaconda# section by using the section again in your custom Kickstart.

[[sect-kickstart-commands-include]]
==== %include (optional) - Include Contents of Another File

Use the [command]#%include _/path/to/file_pass:attributes[{blank}]# command to include the contents of another file in the Kickstart file as though the contents were at the location of the [command]#%include# command in the Kickstart file.

[[sect-kickstart-commands-ksappend]]
==== %ksappend (optional) - Append Contents of Another File

The [command]#%ksappend _url_pass:attributes[{blank}]# directive is very similar to xref:sect-kickstart-commands-include[%include (optional) - Include Contents of Another File] in that it is used to include the contents of additional files as though they were at the location of the [command]#%ksappend# command. The difference is in when the two directives are processed.

[command]#%ksappend# is processed in an initial pass, before any other part of the Kickstart file. Then, this expanded Kickstart file is passed to the rest of [application]*Anaconda* where all [command]#%pre# scripts are handled, and then finally the rest of the Kickstart file is processed in order, which includes [command]#%include# directives.

Therefore, [command]#%ksappend# provides a way to include a file containing [command]#%pre# scripts, while [command]#%include# does not.

[[sect-kickstart-packages]]
==== %packages (required) - Package Selection

Use the [command]#%packages# command to begin a Kickstart section which describes the software packages to be installed. This section must end with an [command]#%end# statement.

You can specify packages by _environment_, _group_, or by their package names. Several environments and groups that contain related packages are defined. See the `repodata/comps.xml` file in your installation source for environment and group definitions.

The `comps.xml` file contains a structure describing available environments (marked by the `<environment>` tag) and groups (the `<group>` tag). Each entry has an ID, user visibility value, name, description, and package list. If the group is selected for installation, the packages marked `mandatory` in the package list are always installed, the packages marked `default` are installed if they are not specifically excluded, and the packages marked `optional` must be specifically included even when the group is selected.

You can specify a package group or environment using either its ID (the `<id>` tag) or name (the `<name>` tag).

[IMPORTANT]
====

To install a 32-bit package on a 64-bit system, you will need to append the package name with the 32-bit architecture for which the package was built - for example, [package]*glibc.i686*. The [option]#--multilib# option also must be specified in the Kickstart file; see the available options below.

====

[IMPORTANT]
====

[application]*Initial Setup* does not run after a system is installed from a Kickstart file unless a desktop environment and the [application]*X Window System* were included in the installation and graphical login was enabled. This means that by default, no users except for `root` will be created. You can either create a user with the [option]#user# option in the Kickstart file before installing additional systems from it (see xref:sect-kickstart-commands-user[user (optional) - Create User Account] for details) or log into the installed system with a virtual console as `root` and add users with the [command]#useradd# command.

====

.Specifying Environments, Groups and Packages

Specifying an Environment::  In addition to groups, you specify an entire environment to be installed:
+
----

%packages
@^Infrastructure Server
%end

----
+
This command will install all packages which are part of the `Infrastracture Server` environment. All available environments are described in the `comps.xml` file.

Specifying Groups::  Specify groups, one entry to a line, starting with an `@` symbol, and then the full group name or group id as given in the `comps.xml` file. For example:
+
[subs="quotes, macros"]
----

[command]#%packages#
@X Window System
@Desktop
@Sound and Video
[command]#%end#

----
+
The `Core` and `Base` groups are always selected - it is not necessary to specify them in the [command]#%packages# section.
+
The `comps.xml` file also defines groups called `Conflicts (_variant_)` for each variant of {PRODUCT}. This group contains all packages which are known to cause file conflicts, and is intended to be excluded.

Specifying Individual Packages::  Specify individual packages by name, one entry to a line. You can use the asterisk character (`*`) as a _wildcard_ in package names. For example:
+
----

%packages
sqlite
curl
aspell
docbook*
%end

----
+
The `docbook*` entry includes the packages [package]*docbook-dtds*, [package]*docbook-simple*, [package]*docbook-slides* and others that match the pattern represented with the wildcard.

Excluding Environments, Groups, or Packages::  Use a leading dash (`-`) to specify packages or groups to exclude from the installation. For example:
+
----

%packages
-@Graphical Internet
-autofs
-ipa*fonts
%end

----

[IMPORTANT]
====

Installing all available packages using only `*` in a Kickstart file is not supported, even if you exclude the `@Conflicts (_variant_)` group.

====

You can change the default behavior of the [command]#%packages# section by using several options. Some options work for the entire package selection, others are used with only specific groups.

.Common Package Selection Options

The following options are available for the [command]#%packages#. To use an option, append it to the start of the package selection section. For example:

[subs="quotes, macros"]
----
[command]#%packages --multilib --ignoremissing#
----

[option]#--nocore#::  Do not install the `@Core` group.

[option]#--ignoremissing#::  Ignore any packages, groups and environments missing in the installation source, instead of halting the installation to ask if the installation should be aborted or continued.

[option]#--excludedocs#::  Do not install any documentation contained within packages. In most cases, this will exclude any files normally installed in the `/usr/share/doc*` directory, but the specific files to be excluded depend on individual packages.

[option]#--multilib#::  Configure the installed system for multilib packages (that is, to allow installing 32-bit packages on a 64-bit system) and install packages specified in this section as such.
+
Normally, on a 64-bit system, only packages for this architecture (marked as `x86_64`) and packages for all architectures (marked as `noarch`) would be installed. When you use this option, packages for 32-bit systems (marked as `i686`) will be automatically installed as well, if available.
+
This only applies to packages explicitly specified in the [command]#%packages# section. Packages which are only being installed as dependencies without being specified in the Kickstart file will only be installed in architecture versions in which they are needed, even if they are available for more architectures.

.Options for Specific Package Groups

The options in this list only apply to a single package group. Instead of using them at the [command]#%packages# command in the Kickstart file, append them to the group name. For example:

[subs="quotes, macros"]
----

[command]#%packages#
@Graphical Internet --optional
[command]#%end#

----

[option]#--nodefaults#::  Only install the group's mandatory packages, not the default selections.

[option]#--optional#::  Install packages marked as optional in the group definition in the `comps.xml` file, in addition to installing the default selections.
+
Note that some package groups, such as `Scientific Support`, do not have any mandatory or default packages specified - only optional packages. In this case the [option]#--optional# option must always be used, otherwise no packages from this group will be installed.

[[sect-kickstart-preinstall]]
==== %pre (optional) - Pre-installation Script

You can add commands to run on the system immediately after the Kickstart file has been parsed, but before the installation begins. This section must be placed towards the end of the Kickstart file, after the actual Kickstart commands, and must start with [command]#%pre# and end with [command]#%end#. If your Kickstart file also includes a [command]#%post# section, the order in which the [command]#%pre# and [command]#%post# sections are included does not matter.

You can access the network in the [command]#%pre# section. However, the _name service_ has not been configured at this point, so only IP addresses work, not URLs.

The pre-installation script section of Kickstart *cannot* manage multiple install trees or source media. This information must be included for each created Kickstart file, as the pre-installation script occurs during the second stage of the installation process.

[NOTE]
====

Unlike the post-installation script, the pre-installation script is not run in the `chroot` environment.

====

The following options can be used to change the behavior of pre-installation scripts. To use an option, append it to the [command]#%pre# line at the beginning of the script. For example:

[subs="quotes, macros"]
----

[command]#%pre --interpreter=/usr/bin/python#
--- Python script omitted --
[command]#%end#

----

[option]#--interpreter=#::  Allows you to specify a different scripting language, such as Python. Any scripting language available on the system can be used; in most cases, these will be `/usr/bin/sh`, `/usr/bin/bash`, and `/usr/bin/python`.

[option]#--erroronfail#::  Display an error and halt the installation if the script fails. The error message will direct you to where the cause of the failure is logged.

[option]#--log=#::  Logs the script's output into the specified log file. For example:
+
[subs="quotes, macros"]
----
[command]#%pre --log=/mnt/sysimage/root/ks-pre.log#
----

For an example of a pre-installation script, see xref:sect-kickstart-example-pre-script[Example Pre-installation Script].

[[sect-kickstart-postinstall]]
==== %post (optional) - Post-installation Script

You have the option of adding commands to run on the system once the installation is complete, but before the system is rebooted for the first time. This section must be placed towards the end of the Kickstart file, after the actual Kickstart commands, and must start with [command]#%post# and end with [command]#%end#. If your Kickstart file also includes a [command]#%pre# section, the order of the [command]#%pre# and [command]#%post# sections does not matter.

This section is useful for functions such as installing additional software or configuring an additional name server. The post-install script is run in a chroot environment, therefore, performing tasks such as copying scripts or RPM packages from the installation media do not work by default. You can change this behavior using the [option]#--nochroot# option as described below.

[IMPORTANT]
====

If you configured the network with static IP information, including a name server, you can access the network and resolve IP addresses in the [command]#%post# section. If you configured the network for `DHCP`, the `/etc/resolv.conf` file has not been completed when the installation executes the [command]#%post# section. You can access the network, but you cannot resolve IP addresses. Thus, if you are using `DHCP`, you must specify IP addresses in the [command]#%post# section.

====

The following options can be used to change the behavior of post-installation scripts. To use an option, append it to the [command]#%post# line at the beginning of the script. For example:

[subs="quotes, macros"]
----

[command]#%post --interpreter=/usr/bin/python#
--- Python script omitted --
[command]#%end#

----

[option]#--interpreter=#::  Allows you to specify a different scripting language, such as Python. For example:
+
[subs="quotes, macros"]
----
[command]#%post --interpreter=/usr/bin/python#
----
+
Any scripting language available on the system can be used; in most cases, these will be `/usr/bin/sh`, `/usr/bin/bash`, and `/usr/bin/python`.

[option]#--nochroot#::  Allows you to specify commands that you would like to run outside of the chroot environment.
+
The following example copies the file `/etc/resolv.conf` to the file system that was just installed.
+
[subs="quotes, macros"]
----

[command]#%post --nochroot#
cp /etc/resolv.conf /mnt/sysimage/etc/resolv.conf
[command]#%end#

----

[option]#--erroronfail#::  Display an error and halt the installation if the script fails. The error message will direct you to where the cause of the failure is logged.

[option]#--log=#::  Logs the script's output into the specified log file. Note that the path of the log file must take into account whether or not you use the [option]#--nochroot# option. For example, without [option]#--nochroot#:
+
[subs="quotes, macros"]
----
[command]#%post --log=/root/ks-post.log#
----
+
with [option]#--nochroot#:
+
[subs="quotes, macros"]
----
[command]#%post --nochroot --log=/mnt/sysimage/root/ks-post.log#
----

For an example of a post-installation script, see xref:sect-kickstart-example-post-script[Example Post-installation Script].

[[sect-kickstart-examples]]
== Example Kickstart Configurations

[[sect-kickstart-example-advanced-partitioning]]
=== Advanced Partitioning Example

The following is an integrated example showing the [command]#clearpart#, [command]#zerombr#, [command]#part#, [command]#raid#, [command]#volgroup#, and [command]#logvol# Kickstart options in action:

.Advanced Partitioning Example
====

----

clearpart  --drives=hda,hdc
zerombr
# Raid 1 IDE config
part raid.11 --size 1000  --asprimary --ondrive=hda
part raid.12 --size 1000  --asprimary --ondrive=hda
part raid.13 --size 2000  --asprimary --ondrive=hda
part raid.14 --size 8000              --ondrive=hda
part raid.15 --size 16384 --grow      --ondrive=hda
part raid.21 --size 1000  --asprimary --ondrive=hdc
part raid.22 --size 1000  --asprimary --ondrive=hdc
part raid.23 --size 2000  --asprimary --ondrive=hdc
part raid.24 --size 8000              --ondrive=hdc
part raid.25 --size 16384 --grow      --ondrive=hdc

# You can add --spares=x
raid /     --fstype xfs  --device root  --level=RAID1 raid.11 raid.21
raid /safe --fstype xfs  --device safe  --level=RAID1 raid.12 raid.22
raid swap  --fstype swap --device swap  --level=RAID1 raid.13 raid.23
raid /usr  --fstype xfs  --device usr   --level=RAID1 raid.14 raid.24
raid pv.01 --fstype xfs  --device pv.01 --level=RAID1 raid.15 raid.25

# LVM configuration so that we can resize /var and /usr/local later
volgroup sysvg pv.01
logvol /var           --vgname=sysvg --size=8000     --name=var
logvol /var/freespace --vgname=sysvg --size=8000     --name=freespacetouse
logvol /usr/local     --vgname=sysvg --size=1 --grow --name=usrlocal

----

====

This advanced example implements LVM over RAID, as well as the ability to resize various directories for future growth.

First, the [command]#clearpart# command is used on drives `hda` and `hdc` to wipe them. The [command]#zerombr# command initializes unused partition tables.

Then, the two drives are partitioned to prepare them for RAID configuration. Each drive is divided into five partitions, and each drive is partitioned into an identical layout.

The next part uses these pairs of physical partitions to create a software RAID device with RAID1 level (mirroring). The first four RAID devices are used for `/` (root), `/safe`, `swap` and `/usr`. The fifth, largest pair of partitions is named `pv.01` and will be used in the following part as a physical volume for LVM.

Finally, the last set of commands first creates a volume group named `sysvg` on the `pv.01` physical volume. Then, three logical volumes (`/var`, `/var/freespace` and `/usr/local`) are created and added to the `sysvg` volume group. The `/var` and `/var/freespace` volumes have a set size of 8 GB, and the `/usr/local` volume uses the [option]#--grow# option to fill all remaining available space.

[IMPORTANT]
====

The above example uses identifiers `hda` and `hdc` to identify disk drives. You should use unique identifiers, such as a disk labels or an UUIDs, to identify disk drives. See the note in introduction to this appendix.

====

[[sect-kickstart-example-pre-script]]
=== Example Pre-installation Script

The following is an example [command]#%pre# section:

[[exam-kickstart-pre-script]]
.Sample %pre Script
====

----

%pre
#!/bin/sh
hds=""
mymedia=""
for file in /proc/ide/h* do
mymedia=`cat $file/media`
if [ $mymedia == "disk" ] ; then
hds="$hds `basename $file`"
fi
done
set $hds
numhd=`echo $#`
drive1=`echo $hds | cut -d' ' -f1`
drive2=`echo $hds | cut -d' ' -f2`

#Write out partition scheme based on whether there are 1 or 2 hard drives
if [ $numhd == "2" ] ; then
#2 drives
echo "#partitioning scheme generated in %pre for 2 drives" > /tmp/part-include
echo "clearpart --all" >> /tmp/part-include
echo "part /boot --fstype xfs --size 75 --ondisk hda" >> /tmp/part-include
echo "part / --fstype xfs --size 1 --grow --ondisk hda" >> /tmp/part-include
echo "part swap --recommended --ondisk $drive1" >> /tmp/part-include
echo "part /home --fstype xfs --size 1 --grow --ondisk hdb" >> /tmp/part-include
else
#1 drive
echo "#partitioning scheme generated in %pre for 1 drive" > /tmp/part-include
echo "clearpart --all" >> /tmp/part-include
echo "part /boot --fstype xfs --size 75" >> /tmp/part-include
echo "part swap --recommended" >> /tmp/part-include
echo "part / --fstype xfs --size 2048" >> /tmp/part-include
echo "part /home --fstype xfs --size 2048 --grow" >> /tmp/part-include
fi
%end

----

This script determines the number of hard drives in the system and writes a text file with a different partitioning scheme depending on whether it has one or two drives. Instead of having a set of partitioning commands in the Kickstart file, include the following line:

[subs="quotes, macros"]
----
[command]#%include /tmp/part-include#
----

The partitioning commands selected in the script will be used.

====

[[sect-kickstart-example-post-script]]
=== Example Post-installation Script

The following is an example [command]#%post# section:

[[exam-kickstart-post-script]]
.Sample %post Script
====

----

# Start of the %post section with logging into /root/ks-post.log
%post --log=/root/ks-post.log

# Mount an NFS share
mkdir /mnt/temp
mount -o nolock 10.10.0.2:/usr/new-machines /mnt/temp
openvt -s -w -- /mnt/temp/runme
umount /mnt/temp

# End of the %post section
%end

----

The above example mounts an NFS share and executes a script named `runme` located at `/usr/new-machines/` on the share. Note that NFS file locking is *not* supported while in Kickstart mode, therefore the [option]#-o nolock# option is required.

====
