
:experimental:
include::{partialsdir}/entities.adoc[]

[[chap-kickstart-installations]]
= Automating the Installation with Kickstart

Kickstart installations offer a means to automate the installation process, either partially or fully. Kickstart files contain answers to all questions normally asked by the installation program, such as what time zone do you want the system to use, how should the drives be partitioned or which packages should be installed. Providing a prepared Kickstart file when the installation begins therefore allows the you to perform the installation automatically, without need for any intervention from the user. This is especially useful when deploying {PRODUCT} on a large number of systems at once.

All Kickstart scripts and the log files of their execution are stored in the `/tmp` directory to assist with debugging installation issues.

[[sect-kickstart-howto]]
== How to Perform a Kickstart Installation

Kickstart installations can be performed using a local DVD, a local hard drive, or via NFS, FTP, HTTP, or HTTPS.

To use Kickstart, you must:

. Create a Kickstart file.

. Create boot media or configure a network boot (PXE) server which will be used to begin the installation.

. Make the Kickstart file available on removable media, a hard drive, or a network location.

. Start the Kickstart installation by booting the installer and using a boot option to tell the installer where to find the Kickstart file.

This chapter explains these steps in detail.

[[sect-kickstart-file-create]]
=== Creating a Kickstart File

The Kickstart file itself is a plain text file, containing keywords listed in xref:appendixes/Kickstart_Syntax_Reference.adoc#appe-kickstart-syntax-reference[Kickstart Syntax Reference], which serve as directions for the installation. Any text editor able to save files as ASCII text (such as [application]*Gedit* or [application]*vim* on Linux systems or [application]*Notepad* on Windows systems) can be used to create and edit Kickstart files.

The recommended approach to creating Kickstart files is to perform a manual installation on one system first. After the installation completes, all choices made during the installation are saved into a file named `anaconda-ks.cfg`, located in the `/root/` directory on the installed system. You can then copy this file, make any changes you need, and use the resulting configuration file in further installations.

When creating a Kickstart file, keep in mind the following:

* Lines starting with a pound sign (`#`) are treated as comments and are ignored.

* Sections must be specified *in order*. Items within the sections do not have to be in a specific order unless otherwise specified. The correct section order is:
+
** The command section which contains actual Kickstart commands and options as listed in xref:appendixes/Kickstart_Syntax_Reference.adoc#appe-kickstart-syntax-reference[Kickstart Syntax Reference]. Note that some commands, such as [command]#install#, are mandatory, but most commands are optional.
+
** The [command]#%packages# section which contains a list of packages and package groups to be installed. See xref:appendixes/Kickstart_Syntax_Reference.adoc#sect-kickstart-packages[%packages (required) - Package Selection] for details.
+
** The [command]#%pre# and [command]#%post# sections, containing a pre-installation and post-installation scripts. These two sections can be in any order and are not mandatory. See xref:appendixes/Kickstart_Syntax_Reference.adoc#sect-kickstart-preinstall[%pre (optional) - Pre-installation Script] and xref:appendixes/Kickstart_Syntax_Reference.adoc#sect-kickstart-postinstall[%post (optional) - Post-installation Script] for details.
+
[IMPORTANT]
====

The [command]#%packages#, [command]#%pre# and [command]#%post# sections must end with [command]#%end#, otherwise the installation program will refuse the Kickstart file. The main command section has no special ending statement.

====

* Omitting any required item results in the installation program prompting the user for an answer to the related item, just as the user would be prompted during a typical installation. Once the answer is given, the installation will continue. Note that if the system you are installing has no display, you will not be able to see the prompt, and the installation will appear to have failed.

[[sect-kickstart-verify]]
=== Verifying the Kickstart File

When creating or customizing your kickstart file, it is useful to verify that it is valid before attempting to use it in an installation. {PRODUCT} includes the [application]*ksvalidator* command line utility which can be used to do this. This tool is a part of the [package]*pykickstart* package. To install this package, execute the following command:

[subs="macros"]
----
# dnf install pykickstart
----

After installing the package, you can validate a Kickstart file using the following command:

[subs="quotes, macros"]
----
$ [command]#ksvalidator _/path/to/kickstart.ks_#
----

Replace _/path/to/kickstart.ks_ with the path to the Kickstart file you want to verify.

For more information about this tool, see the `ksvalidator(1)` man page.

[IMPORTANT]
====

Keep in mind that the validation tool has its limitations. The Kickstart file can be very complicated; [application]*ksvalidator* can make sure the syntax is correct and that the file does not include removed options, but it cannot guarantee the installation will be successful. It also does not attempt to validate the [command]#%pre#, [command]#%post# and [command]#%packages# sections of the Kickstart file.

====

[[sect-kickstart-making-available]]
=== Making the Kickstart File Available

Once you create a Kickstart file, you can place it in one of the following locations:

* On *removable media*, such as a DVD or USB flash drive connected to the installation system

* On a *hard drive* connected to the installation system

* On a *network share* reachable from the installation system

Normally, a Kickstart file is copied to removable media or a hard drive, or made available on the network. Placing the file in a network location complements the usual approach to Kickstart installations, which is also network-based: the system is booted using a PXE server, the Kickstart file is downloaded from a network share, and software packages specified in the file are downloaded from remote repositories.

xref:advanced/Network_based_Installations.adoc#chap-pxe-server-setup[Setting Up an Installation Server] offers some additional information about preparing for a network-based installation.

[[sect-kickstart-installation-starting]]
=== Starting the Kickstart Installation

Once you have everything ready - you have created a valid Kickstart file and you have either local boot media or a PXE server available, you can start the Kickstart installation. You need to use the [option]#inst.ks=# boot option either in the boot menu (when booting from local media), or add this option to your PXE server configuration. For information about boot options used in Kickstart installations, see xref:advanced/Boot_Options.adoc#sect-boot-options-kickstart[Kickstart Boot Options].
