
:experimental:
include::{partialsdir}/entities.adoc[]

[[chap-upgrading]]
= Upgrading Your Current System

This chapter explains how to upgrade your existing {PRODUCT} installation to the current release. There are two basic ways to do so:

Automatic upgrade using [application]*dnf system upgrade*::  The preferred way to upgrade your system is an automatic upgrade using the [application]*dnf system upgrade* utility. For information on performing an automatic upgrade, see link:++https://fedoraproject.org/wiki/DNF_system_upgrade++[Fedora Wiki DNF system upgrade].

Manual Reinstallation::  You can upgrade to the latest version of Fedora manually instead of relying on [application]*dnf system upgrade*. This involves booting the installer as if you were performing a clean installation, letting it detect your existing Fedora system, and overwriting the root partition while preserving data on other partitions and volumes. The same process can also be used to reinstall the system, if you need to. For detailed information, see xref:sect-upgrading-fedora-manual-reinstall[Manual System Upgrade or Reinstallation].

[WARNING]
====

Always back up your data before performing an upgrade or reinstalling your system, no matter which method you choose.

====

[[sect-upgrading-fedora-manual-reinstall]]
== Manual System Upgrade or Reinstallation

Unfortunately, we have not written this chapter yet, and there is no dedicated documentation about a manual reinstall on the Wiki, either. In the meantime before we fix this, you can try to start the installation normally (from a boot CD/DVD/USB), select manual partitioning in your installer, and reuse existing partitions instead of destroying them and creating new ones. The instructions at xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-manual-partitioning[Manual Partitioning] should in most cases be easy to adapt for this.
