
:experimental:

[[sect-installation-gui-network-configuration-virtual-interface]]
==== Adding a Virtual Network Interface

To add a virtual network interface, click the `+` button at the bottom of the interface list. A new window will open, prompting you to select one of the three available types of virtual interfaces:

* `Bond` - NIC (_Network Interface Controller_) Bonding, a method to bind multiple physical network interfaces together into a single bonded channel.

* `Team` - NIC Teaming, a new implementation to aggregate links, designed to provide a small kernel driver to implement the fast handling of packet flows, and various applications to do everything else in user space.

* `Vlan` (_Virtual LAN_) - A method to create multiple distinct broadcast domains which are mutually isolated.

Select the interface type you want to add, and click `Add`. Another dialog window will open, allowing you to edit any available settings for your chosen interface type. For information about available settings, see the respective sections of the [citetitle]_{PRODUCT} Networking{nbsp}Guide_, available at link:++https://docs.fedoraproject.org/++[]. Basic documentation is also available in xref:install/Installing_Using_Anaconda.adoc#sect-installation-gui-network-configuration-advanced[Editing Network Interface Configuration].

[NOTE]
====

To access the settings dialog again after you closed it, select the same interface in the list of configured interfaces and click `Configure` in the bottom right corner of the screen. To remove a virtual interface, select it in the list and click the `-` button below.

====
